### ISSUE TITLE
Create SPED referral form

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#100]
*“I can print the student profile out and that can be my student referral”* - Curriculum Coordinator

**Information required in referrals include but not limited to:**
- demographics
  - birthdate
  - birthplace
  - language
  - disability
  - SPED referral
  - 504 plan
- attendance
  - prior school enrollments
  - days present this school year
  - days absent this school year
  - retention
  - other information including irregular attendance, frequent tardiness, transience in elementary school, etc
- grades
  - report cards
- assessment
  - dates administered
  - scores
- behavior/discipline
  - number of discipline reports
  - number of suspensions (in-school and out-of-school)
- interventions
  - evidence of RTI (response to interventions)
- health

Issues related to student profile: #63 #72

**Comment by alexsoble** [comment]
This is fantastic @marimuraki.  Let's scan what the form looks like when you bring the hard copy into the office.

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: As discussed today with State SPED, our highest value-added would be in create more user-friendly & efficient ways for teachers/admins and parents to interact with the SPED forms. 

- *"mad-lib style"*
- *"answers are what matter"*

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights.
