### ISSUE TITLE
Investigate / import MCAS results via X2

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#102]
+ [ ] **Question**: How far back do historical MCAS results go in X2? 
+ [ ] **Question**: What information do we have? i.e. summary stats, item-by-item results
+ [ ] **Question**: What is the quality of the data?
+ [ ] **ToDo**: Write SQL script to send to John Breslin to export MCAS via X2

**Comment by marimuraki** [comment]
@alexsoble: Working on debugging InnoDB error. Not able to access files on MySQL server. `Unknown table engine InnoDB`.

**Comment by marimuraki** [comment]
@alexsoble: Ben helped debug the `Unknown table engine InnoDB` error.

For future reference:

+ Create a configuration file

`sudo cp /usr/local/mysql/support-files/my-small.cfn /etc/my.cfn`

+ Uncomment the innodb-related lines in the configuration file
+ Add the following to the [mysqld] section:

`default-storage-engine = innodb`
`innodb_force_recovery = 6`

**Comment by marimuraki** [comment]
SQL  query for `student_assessment` table:

`SELECT ASM_STD_OID, ASM_SKL_OID, ASM_ASD_OID, ASM_DATE,
ASM_SCALE_SCORE, ASM_PERFORMANCE_LEVEL, ASM_GRADE_LEVEL_CODE
FROM student_assessment;`

**Comment by marimuraki** [comment]
The `ASM_ASD_OID` seems to be the assessment test but we may need a data dictionary because the values are not self-evident. Let me play with it more and see if I can figure out which one refer to the MCAS reading and math assessments.

`SELECT DISTINCT ASM_ASD_OID FROM student_assessment;`

**Comment by marimuraki** [comment]
Got it. In addition to the `student_assessment` table, you also need the `assessment_definition` table to identify the assessment name `ASD_NAME` e.g., MCAS, DIBELS, MEPA, MELA, SAT, ACT, AP, etc.

`SELECT ASD_OID, ASD_NAME, ASD_SUBJECT FROM assessment_definition;`

Merge the `student_assessment` table and `assessment_definition` table using `ASM_ASD_OID` and `ASD_OID`, respectively.

**Comment by marimuraki** [comment]
`ASD_OID` and `ASD_NAME` are specific to assessment, subject, and year (!) so either we can subset to the specific `ASD_OID` or we can parse the `ASD_NAME` for the first word = assessment.  Unfortunately `ASD_TYPE` is missing for assessments we are interested in i.e., MCAS, STAR.

**Comment by marimuraki** [comment]
Joining `student_assessment` & `assessment_definition`:

`SELECT DISTINCT ASM_STD_OID, ASM_SKL_OID, ASM_ASD_OID, ASM_DATE,` `ASM_SCALE_SCORE, ASM_PERFORMANCE_LEVEL, ASD_NAME, ASD_SUBJECT,`
`SUBSTRING_INDEX(SUBSTRING_INDEX(ASD_NAME, ' ', 1), ' ', -1) as ASD_TEST 
FROM student_assessment`
`LEFT JOIN assessment_definition
ON student_assessment.ASM_ASD_OID=assessment_definition.ASD_OID;` 

The variable `ASD_TEST` identifies the assessment (without the additional subject and/or year information included in `ASD_NAME`).

@alexsoble: This is for all students in `student_assessment`, does not exclude INACTIVE students.

**Comment by marimuraki** [comment]
@alexsoble: Added [assessment_export.sql](https://github.com/codeforamerica/somerville-teacher-tool/blob/master/x2_export/assessment_export.sql) following the other export structures.

**Comment by marimuraki** [comment]
Pulling in MCAS assessment data from X2 as recommended by Uri --- rather than pulling it in from Edwin Analytics' DropBox --- we see many more ASM_PERFORMANCE_LEVEL values. Compared to the 4 levels of {A, P, NI, W} we've pulled in from the Edwin files, the ASM_PERFORMANCE_LEVEL from X2 takes many values. 

**How do we map these values onto {A, P, NI, W}?** @alexsoble 

- A
- ABS
- AWR
- Advanced
- DNT
- EMG
- F
- INC
- INE
- INP
- INV
- LEP
- MED
- NI
- NIA
- P
- P+
- PRF
- PRG
- Proficient
- TRN
- VAB
- W
- \N

**Comment by marimuraki** [comment]
**General Assessment:**

- W = Warning
- NI = Needs Improvement
- P = Proficient
- A = Advanced

**Alternate Assessment:**
- INP = Incomplete
- AWR = Awareness
- EMG = Emerging
- PRG = Progressing
- NIA = Needs Improvement
- P_A = Proficient
- A_A = Advanced

**Others:**
- ABS = Absent
- MED = Medically Documented Absence
- TRN = Transferred
- LEP = First year LEP
- INC = Incomplete
- VAB = Void answer
- DUP = Multiple answer booklets

[Link](http://www.mcasservicecenter.com/documents/MA/Technical%20Report/2010/Appendix%20S%20-%20Analysis%20and%20Reporting%20Decision%20Rules%20-%20MCAS.pdf)

**Comment by marimuraki** [comment]
@alexsoble: The `state_id' is not consistent between the assessment file and the {attendance, behavior, student} files. Need to look into this. Sorry I missed this until now.

**Comment by marimuraki** [comment]
@alexsoble: Think the solution is that we need to pull the following variables from the {attendance, behavior, student} files. We can review this together.

- student: `STD_OID`
- student_attendance: `ATT_STD_OID`
- student_conduct_incident: `CND_STD_OID`

Relates to #80

**Comment by alexsoble** [comment]
@marimuraki No sweat! Was planning on talking with you about this today. :relaxed:

**Comment by alexsoble** [comment]
@marimuraki: https://github.com/codeforamerica/somerville-teacher-tool/commit/776aeab58ad914efc215d3bb274f6bacd0f10bf7

I think we should use state IDs instead of local IDs for students. More reliable and extensible.

**Comment by alexsoble** [comment]
@marimuraki 

A few that seem to be missing from the MAP: DNT (guessing that's Did Not Test), F, INV, P+

**Comment by marimuraki** [comment]
@alexsoble: Are these values also in MCAS?

- P+: Above Proficient
- INV: Invalidated
- F: Failing
- DNT: Did Not Test

[Reference](http://www.mcasservicecenter.com/documents/MA/Technical%20Report/2013/Appendices/Appendix%20T%20-%20Analysis%20and%20Reporting%20Decision%20Rules%20-%20MCAS-Alt.pdf)

**Comment by marimuraki** [comment]
![screenshot 2015-06-16 12 01 40](https://cloud.githubusercontent.com/assets/1334815/8191916/c6ecd93a-141f-11e5-9a0d-1c27e7b77eab.png)
![screenshot 2015-06-16 12 01 51](https://cloud.githubusercontent.com/assets/1334815/8191917/c6ed49f6-141f-11e5-9822-ba5625bbae31.png)

[Reference](http://www.mcasservicecenter.com/documents/MA/Technical%20Report/2013/Appendices/Appendix%20T%20-%20Analysis%20and%20Reporting%20Decision%20Rules%20-%20MCAS-Alt.pdf)

**Comment by alexsoble** [comment]
Since we don't have MCAS growth information in the most recent export, we should:

* [ ] See if growth information is stored somewhere unexpected in X2 and add it to the export
* [ ] If not, see if Somerville can add MCAS growth scores to X2 `student_assessment` table
* [ ] If neither of the above works, use scaled score and drop growth score

**Comment by marimuraki** [comment]
@alexsoble: growth scores are *"SGP is in the other score field, asmFieldB001"* - John Breslin
