### ISSUE TITLE
An aggregated view of school system info for parents/the public?

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#106]
Idea from @coderica at SF Brigade!

**Comment by marimuraki** [comment]
View for parent:
- specific to child
- used in parent-teacher conferences
- include or not to include classroom comparisons?
  - I don't remember if I read it in a news article or a research paper but I recall reading about how showing parents classroom comparisons on which to benchmark their child's performance can have negative consequences in terms of creating competitive environments. Let me try to track it down.

**Comment by marimuraki** [comment]
This is not the article I was thinking of but is relevant to the conversation and definitely something to keep in mind when we think about how data is used, shared, interpreted, etc:

http://www.washingtonpost.com/blogs/answer-sheet/wp/2014/02/14/how-data-walls-in-classrooms-can-humiliate-young-kids/
http://www.washingtonpost.com/blogs/answer-sheet/wp/2014/02/21/how-some-school-data-walls-violate-u-s-privacy-law/

**Comment by alexsoble** [comment]
This is a great idea, would love to do on a future iteration. Out of scope for right now though.
