### ISSUE TITLE
Should we have a Twitter feed / Facebook page?

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#107]
Ideas from @coderica & Tyler at Code for SF! 

+ "Who can we rope in to get their ideas?"
+ "Communicate to non-tech people."
+ "Communicate to teachers, parents, students"
+ "A central place where people can see what's going on with that project..."
+ "Project site that can be handed out"

**Comment by marimuraki** [comment]
Yes, definitely a great idea to get more ideas. I think for **now** we should connect more strategically rather than sending out a wide net i.e., Healey team > Healey teams > Healey School > schools+ > district (including parents and students) PLUS Code for [X] + partners.

**Comment by marimuraki** [comment]
What do you think of doing a survey similar to Gates Foundations / IDEO's http://teachersknowbest.org/ to understand preferences/needs & ideas? It can be targeted to Somerville but also can span a wider population.

**Comment by marimuraki** [comment]
At EdCamp, one session discussed how teachers learn about new education technology. Many teachers said Twitter was their main source of information through social media.

**Comment by marimuraki** [comment]
@CodySF this definitely falls in your expertise! What do you think about outreach via Twitter / Facebook? Right now, most of our contributions are in-person or on GitHub.

**Comment by CodySF** [comment]
Hey! Interesting idea. Are you thinking that we could use Twitter / Facebook to find more contributors with ideas? Or more to validate the Student Insights tool / better understand teacher preferences/needs & ideas?

**Comment by marimuraki** [comment]
@CodySF: I think we want to find a way to get a really targeted feedback from users, first teachers (and later parents, students, etc). I haven't used Twitter / Facebook for other than personal things so not sure how to make sure we don't get too inundated (although probably not a high probability of that happening).

[LearnLaunch](http://learnlaunch.com/), an ed-tech startup based in Boston, holds a lot of events where educators (teachers, instructional tech leaders, etc) participate. I've been to one of their EdSurge + LearnLanuch conferences and there is a ton of great ideas being shared. What are ways we can get that sort of feedback over a more open forum like Twitter / Facebook?

@alexsoble @AmirHadjihabib: Ideas?

**Comment by alexsoble** [comment]
I think targeted feedback is exactly right. I've been chatting with @CodySF about developing some questions that we could ask other school districts about how they use data: understanding needs in different school districts as we work with Somerville. One we develop some of those questions and refine them over time, maybe we could use social media to share questions & get feedback from teachers, principals, administrators. Targeted but public — future state though, not for right now

**Comment by alexsoble** [comment]
Closing for now until we develop questions to use with other teachers / school leaders / district leaders.
