### ISSUE TITLE
Check data against official DOE numbers

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#112]
It's good to do a **sanity check** against "official" numbers. In my Stanford research, I always cross-checked numbers calculated based on district data against those calculated by the State based on official accountability data --- it helped me catch data discrepancies / issues (especially when you're not intimately familiar with *"Oh, the ELL population at School X should be around Y%"* to think *"Hmmm that look strange"*.) 

For example: do our numbers for Healey school attendance rates fall in line with the [Mass DOE numbers](http://profiles.doe.mass.edu/profiles/student.aspx?orgcode=02740075&orgtypecode=6&leftNavId=303&)?

This is also why it's important to have principals, teachers, etc look at their own data since they are the ones who know their schools / classrooms the best.

Related to #106 for aggregate school-level stats.

**Comment by alexsoble** [comment]
@marimuraki — This is fantastic. We should write these checks together in Ruby and incorporate them into the app. I'm thinking the sanity check could live as a rake task that would run periodically against the data. Agreed that this is related to #106 — the results could certainly be public.

**Comment by marimuraki** [comment]
@Noah-T: Thanks for offering to help with this issue!

We are interested in school-level numbers on (here is Healey example to start with):

- [Indicators](http://profiles.doe.mass.edu/profiles/student.aspx?orgcode=02740075&orgtypecode=6&leftNavId=303&)
  - grade 9-12 dropout rate
  - **attendance rate**
  - **average # of days absent**
  - **absent 10 or more days**
  - **chronically absent (10% or more)**
  - **unexcused absences > 9**
  - retention rate
- [Selected Population](http://profiles.doe.mass.edu/profiles/student.aspx?orgcode=02740075&orgtypecode=6&leftNavId=305&)
  - first language not English
  - **English Language Learner**
  - **Students with Disabilities**
  - High Needs
  - **Economically Disadvantaged**
- [Student Discipline](http://profiles.doe.mass.edu/ssdr/default.aspx?orgcode=02740075&orgtypecode=6&=02740075&)
  - All students: disciplined, **suspension**, **out-of-school suspension**, **expulsion**
- [Assessment](http://profiles.doe.mass.edu/mcas/achievement_level.aspx?linkid=32&orgcode=02740075&orgtypecode=6&)
  - **school-level**
  - **grade-level**

Priorities **bolded** for running comparison tests but might as well pull in all DOE data while you're at it.

**Comment by marimuraki** [comment]
@Noah-T: For district-level comparisons, we have some Excel files (YAY!). [Here](http://www.doe.mass.edu/infoservices/reports/enroll/#) are the files for enrollment numbers by district.

**Comment by Noah-T** [comment]
http://profiles.doe.mass.edu/state_report/indicators.aspx

**Comment by Noah-T** [comment]
http://profiles.doe.mass.edu/profiles/student.aspx?orgcode=02740075&orgtypecode=6&leftNavId=303

**Comment by marimuraki** [comment]
[Exportable table](http://profiles.doe.mass.edu/state_report/indicators.aspx?mode=school&orderBy=) of indicators by school. YAY!

**Comment by Noah-T** [comment]
@alexsoble are you still around? I have some questions.

**Comment by alexsoble** [comment]
@Noah-T — Sorry I didn't get to get back to you on this way back when!

Latest thinking with @kevinrobinson — this would be most useful if it could be automated on both ends. i.e., Student Insights outputs aggregates and checks them against figures that have been automatically scraped or downloaded from the MA DOE site. That way the app could constantly be checking for major discrepancies rather than this being a one-time check.

This automated route could be a really good Code for Boston project!

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/19.
