### ISSUE TITLE
Add commenting in student profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#118]
@alexsoble asked:

- Would it be useful to have a "commenting" function in the student profile?  This would let you as a teacher add descriptive, qualitative comments alongside the data to help frame what the data means.
- Would this be useful to you as a teacher?
- Would it be useful to have comments from past years left by other teachers?

**5th grade Healey team responded:**

*"Comments would also be a great thing to add. This way it gives the teacher an option to add in more specific detail about the student if it is necessary."*

**Comment by alexsoble** [comment]
:+1: :+1: :+1: 

Empowers teachers to give the data qualitative meaning.

**Comment by sgup** [comment]
Hi @alexsoble and @marimuraki, I just went to my first Code for Boston meeting, and I can take up this issue.

Any particular way you want this implemented on the page?

- Shridhar

**Comment by alexsoble** [comment]
Hi @sgup! Thank you for offering to help!

@AmirHadjihabib, what do you think about creating mockups for how this feature should look?

**Comment by alexsoble** [comment]
@sgup: Our designer @AmirHadjihabib is out of the office for a bit. He'll be back next Wednesday. When he's back he'll create designs of this feature that you can work from. Thanks for your offer to help!

**Comment by marimuraki** [comment]
@AmirHadjihabib @alexsoble: Uri describes the comment box priority as such ...

*"Add a Progress Notes/Comments Box, in addition to the description of the intervention box, which teachers/teams could continually add to – sort of a running record showing how the intervention is going and additional notes."*

**Comment by alexsoble** [comment]
Already implemented, I forgot to update this issue.
