### ISSUE TITLE
Overlay data on student profile graph or dashboard view

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#119]
In our meeting with the Healey 5th grade team yesterday, we heard feedback that the graph would be even more useful if different data series could be overlaid onto the same graph. That would let them see historical information about attendance, assessments, and behavior in the same view and look for patterns. Each data series would be turned on or off with a mulitselect. 

A few reference points:

Highcharts compare
http://www.highcharts.com/stock/demo/compare

Google Finance graphs
https://www.google.com/finance?q=INDEXDJX%3A.DJI%2CINDEXSP%3A.INX%2CINDEXNASDAQ%3A.IXIC&ei=Y0xuVZnjBs3nqAHSsoLQDQ

**Comment by thfield** [comment]
@alexsoble I added test results to the student view page and included all datasets on one chart.  I'm not too familiar with highcharts, but the test results should be on a separate scale.

![screen shot 2015-06-04 at 8 29 06 pm](https://cloud.githubusercontent.com/assets/4649503/7998974/21646796-0af9-11e5-9587-60dea0b4643b.png)

The branch is [demo-data-refinement](https://github.com/thfield/somerville-teacher-tool/tree/demo-data-refinement) and requires a migration to get working.  Didn't want to do a pull request as I had to wing how the testing works, so think of this as more of a demonstration

**Comment by alexsoble** [comment]
Hey @thfield! This screenshot raised lots of good questions! @marimuraki @AmirHadjihabib and I were debating & discussing them this morning. Here are some of the questions we are wondering about: 

* What makes sense to compare?
* How do we display data in a way that maximizes insight but minimizes overload/confusion?

Also cc'ing @jsgeiser. Let us know what you think about the concept of combining different data series into one graph. Have you seen any examples where this is done really well? Or poorly?

**Comment by jsgeiser** [comment]
I like this way of looking at the data. I haven't seen it done before where the teacher can create the graph with data they would like to see. Would it be possible to click on the data points they want to put in the graph to show at one time? For example, if a teacher wants to compare only absences and math growth, they would click on those two boxes. Then they can add (e.g. ELA growth) if they want by clicking on that box. They would then have control over what appears at the same time. Would that work?

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib What do you think of overview dashboard view to address the teachers ask for e.g., attendance and scores are correlated by having a single graph that displays these two metrics. One way we may do this without creating complicated overlays of different metrics is to do a dashboard view.

Here is Miguel's suggestion:

*"I imagine you played with the idea of including 5 small graphs (one for each topic), creating a dashboard for each student. I like that approach because it gives you that overview across years and across topics. If the user clicks on one of those smaller graphs you could expand and display it as it is now."*

What do you think?

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: What do you think of something like this? Not a priority but an idea of how to address the teachers & principals feedback on wanting to see the relationship between [X] vs [Y] over time.

- How is my student's performance related to his/her attendance over time?
- How is my student's performance related to his/her behavior incidents over time?

<img width="568" alt="screenshot 2015-08-14 09 01 08" src="https://cloud.githubusercontent.com/assets/1334815/9278075/09b77524-4263-11e5-95fd-5394b4ea5ee9.png">

**Comment by jsgeiser** [comment]
Seeing this kind of relationship would be helpful. I would have it as an option to create (e.g. select boxes of what you want to see, attendance and MCAS, or behavior and STAR, etc.) and not necessarily on a main page.

**Comment by alexsoble** [comment]
@marimuraki @jsgeiser – I agree that having this on a separate page (not necessarily the main page) is a good idea. Too many graphs on the profile would make it very busy. I also think we should put this feature idea on hold for now, lower priority compared to the other features we need to build in order to launch and test the tool at Healey school.

**Comment by alexsoble** [comment]
@marimuraki — These spark notes you designed! They are going into the next iteration of the student profile. Check it out: https://github.com/codeforamerica/somerville-teacher-tool/issues/373#issuecomment-175105589

Last year I was nervous about adding too much front-end complexity too fast, but with @kevinrobinson on board we have been shipping fantastic front-end features in leaps and bounds. Thanks to him now is a great time to add this feature.
