### ISSUE TITLE
Investigate in-class assessments

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#120]
In our last meeting with the Healey teacher team, Ellen mentioned in-class assessments stored in X2.

+ How are in-class assessments stored?
+ What is the quality of the data?
+ What is the difference between in-class assessments and grades?

**Comment by marimuraki** [comment]
Sam mentioned how being able to add in-class assessments would add a lot of value to the tool. Where now she would only look at the tool a few times a year (when the STAR and MCAS assessments are released) and at most 1x/month to look at behavior, if she could see or add her in-class assessments, she would use the tool on a weekly basis. @alexsoble @AmirHadjihabib

**Comment by alexsoble** [comment]
Huge opportunity here. This requires cooperation with classroom teachers. Let's finish the current thread of work first (which includes roles and access for classroom teachers and admins) and then turn our attention to this feature.
