### ISSUE TITLE
Grade-level view for classroom teachers

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#123]
**Teachers share students so it would be helpful to see how students who may not be in their homeroom but who they teach are doing.** 

Healey 5th grade teachers said that it would helpful to see students in the grade level, not only within a given homeroom, which would promote the cross-classroom collaborations that happen within grade level.

**Comment by marimuraki** [comment]
@alexsoble: We need to pull in teacher-grade-homeroom structures. We also need to understand scoping at the elementary, middle and high school levels e.g., would we include course-specific classrooms for upper levels?

**Comment by ejegg** [comment]
Some classrooms may include students of multiple grades, so I'd just associate the grade level with the student.  I plan to a grade_level table with 'name' and 'order' columns, with an FK from students (replacing the 'grade' column).  Then in the roster I'd just make the 'Homeroom' label a dropdown with 'homeroom' and 'grade', which would drive the options available in what's now the homeroom dropdown.  We *could* make the homeroom/grade level a multiselect, but that might be needless UI complication.

Also, hello!  I'd like to help on this project.  I live in Somerville and am just now getting back into Code for Boston meetings.  My Ruby skills are rusty, (and Rails still feels like black magic), but I've got the app running on my dev machine and hope to have a pull request for you soon.

**Comment by marimuraki** [comment]
During my meeting with principals, they mentioned how grade-level views of rosters would be useful.

https://github.com/codeforamerica/somerville-teacher-tool/issues/169

In addition to grade-level roster views, a summary box that gives a quick overview of the students e.g., "X students are Risk 3", "X students are in Warning on MCAS", etc.

**Comment by alexsoble** [comment]
This feature goal has been met for principals and district admins by the school overview dashboard. It lets them view a students by grade levels.

For classroom teachers who don't have permissions to view all students schoolwide, we have two options:

+ Give them access to a version of the school overview dashboard scoped to their grade level
+ Revise the roster page to allow grade-level access

This is future decision to make once more teachers are using the tool and giving us a constant stream of feedback.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/21.
