### ISSUE TITLE
Survey / social-emotional information?

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#125]
All of the student insights so far are based on assessments, behavior, attendance. 

Would it be useful to bring in survey data that reflects students' voice & opinion?  Student feedback?

Social-emotional information to add more depth to the numbers? 

What kind of survey / social-emotional information does Somerville create right now?

Would teachers find this useful? Would students?

**Comment by marimuraki** [comment]
Closing this for now. Out of our current scope.
