### ISSUE TITLE
Integrate out-of-school & other interventions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#126]
We heard from teachers how important interventions e.g., after-school tutoring programs are in supporting student learning.

Also we heard how *"4% of after-school population low-income but 60% of school population low-income"*.

How can we build into the tool connections between in-school and out-of-school programs?

**Comment by marimuraki** [comment]
Let’s refocus on the importance of integrating **out-of-school** data. The value-added of the project — and the vision of City of Somerville / SPS — is to create an understanding of the **“whole child”** i.e., not only how the child is doing in school but the bigger picture of the child in order to best support a child from cradle through career.

- **Out-of-School Factors**
  - Boys and Girls Club
  - YMCA
  - after-school tutoring
- **Family Factors** (from CAAS)
  - income
  - public housing status
  - federal income assistance

**Comment by marimuraki** [comment]
Closing this for now. Out of our current scope.

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Re-opening this issue now that we have some Afterschool Tutoring Program (ATP) data.

ATP data file includes:
- school name
l- ocal student ID (some missing)
- student name
- grade
- **tutor group**
- room number
- **accumulated hours**
- program assigned (this looks like it is the same as what we pulled from X2 -- it's not an ATP program)
- home language
- homeroom teacher

The new ATP-specific data are **bolded**.

Let's go over the data together and see if we have any follow-up questions. A few I have:

- why are some students missing local student IDs?
- how often is this report updated?
- is accumulated hours the number of hours up to the date of data export?

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Things to keep in mind about ATP tutoring process based on convo with Marian. We should talk to her more specifically about the process of:

- how are students identified as needing ATP? e.g., criteria for ATP eligibility
- how do the risk levels, if at all, play a role in identifying ATP eligibility?
- how are students referred to ATP?
- who refers students to ATP? 

It would be interesting to see if she has her own stats on enrollment, retention, dropout, etc to see if it aligns with what we initially found.

We have some basic understanding of the ATP program:

- *We track attendance carefully in this program.* 
- *Each child receives, ideally, 25 hours of tutoring over the year after school.* 
- *The program usually begins in October and wraps up by April.*
- *Each year, there's always some shifting of enrollment, especially at the larger elementary schools.*
- *A student might start later than others for any number of reasons...a move in the middle of the year, a change in their schedule, or possibly the tutor group started later than others.*
- *Tutors don't all start on the same exact date. We allow some flexibility in start date but generally don't allow groups to start too late in the fall, otherwise the tutor can't fit 25 sessions into the academic year.*
- *We try to have tutors finish before MCAS exams (late April to early May).*
- *Also, it's good to finish by April as ATP attendance is more likely to decrease with the better weather.*
- *I only receive the names of children to enroll in ATP (or upload to Scout).* 
  - *The lists are given to me by the ATP coordinator from each school.*
  - *The coordinators also provide me with the rosters for each tutor group (5 children max) as this is another set-up step I do in Scout so tutors can enter attendance for their group over the year.*
  - *Principals, teachers, and the tutor coordinators work together to carefully create these rosters.*

**Comment by alexsoble** [comment]
Two parts here:

+ __ATP data__: Worth fully productionizing at some point in the future, tracked in #305
+ __Non-ATP data__: Out of scope for the current project iteration, need to make this more specific and zero in on the highest-value data sources after ATP
