### ISSUE TITLE
Define risk levels

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#133]
How are risk levels currently calculated by the school district for low, medium, high risk?

**Comment by marimuraki** [comment]
According to Kenya's "Roster Determinations" (mutually exclusive):

- **Risk 0**: Advanced in math, Advanced in ELA, or > 85% on math or ELA MAPS (now STAR)
- **Risk 1**: if not Risk 0 or Risk 2 or Risk 3
- **Risk 2**: *"if a student scores Strategic (SPRING CORE LEVEL), Needs Improvement in math, Needs Improvement in ELA, or below 30% on the math or ELA MAPS (now STAR) assessment"*
- **Risk 3**: Intensive (SPRING CORE LEVEL), Warning or Failing in math, Warning or Failing in ELA, < 10% on the math or ELA MAPS (now STAR) or Limited English Proficient

**Other Measures (ACCESS SGP, DIBELS, MAPS, Attendance)**
- Color Categories: (0) Dark Green, (1) Light Green, (2) Yellow, (3) Red

**ACCESS SGP, MAPS, Attendance**
- (0) > 80
- (1) between 60-80
- (2) between 20-40
- (3) between 60-80

**Note**: 40-60 not color coded

**DIBELS**
- (1) core
- (2) strategic
- (3) intensive

Reference: "Roster Determinations_Risk-Attendance-ACCESS.docx"
Notes: Need to look into how MS Access defined "is between" e.g., includes or excludes bounds

@alexsoble: Following up with Kenya on new rules based on STAR (instead of MAPS).

**Comment by marimuraki** [comment]
**MAPS to STAR**

"The cutoffs are exactly the same for STAR. So you can use the same rules you already have." - Kenya

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Revisiting this question / feedback from Uri about including the risk levels {low, medium, high}.

**"Include risk levels in there that Kenya uses in the rosters - people have gotten very used to seeing those"**

Thoughts?

**Comment by marimuraki** [comment]
Talk to Kenya about how risk levels are defined? Seems strange to use OR.

For example, a student can be Risk 0 if only one indicator is high.
- MCAS ELA: "Advanced"
- MCAS Math: "Warning"
- STAR ELA: 0
- STAR Math: 0

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Order matters so based on Kenya's MS Access rules, Risk Level 3 is run last so takes priority i.e., overwrites the other Risk Levels.

**Comment by marimuraki** [comment]
@alexsoble: Think the ordering should be changed to ... Let's discuss tomorrow.

	  def risk_level
	    # As defined by Somerville Public Schools
	
	    if latest_mcas.present? || latest_star.present?
	      mcas_math = latest_mcas.math_performance
	      mcas_ela = latest_mcas.ela_performance
	      star_math = latest_star.math_percentile_rank
	      star_ela = latest_star.reading_percentile_rank
	
	      if mcas_math == "W" || mcas_ela == "W" || mcas_math == "F" || mcas_ela == "F" ||
	        star_math < 10 || star_ela < 10 || limited_english_proficiency == "Limited"
	        3
	      elsif mcas_math == "NI" || mcas_ela == "NI" || star_math < 30 || star_ela < 30
	        2
	      elsif mcas_math == "A" || mcas_ela == "A" || star_math > 85 || star_ela > 85
	        0
	      else
	        1
	      end
	    end
	  end

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: **Feedback on risk levels**

Show risk levels as 3, 2, 1 (or keep High, Medium, Low). Uri says that the vocabulary used with teachers around risk levels is 3 = High, 2 = Medium, 1 = Low.  He wants to keep a consistent language so teachers and school leaders have a shared language for communicating risk. *"This will correspond to what teachers are doing now and they won't have to think of it as something completely different."*

**Comment by alexsoble** [comment]
@marimuraki – Fixed via https://github.com/codeforamerica/somerville-teacher-tool/commit/60d92d06924b73ed6ed9911bc2f3d9bf0e46b070. Here's how the risk indicators look now:
![new numbers](https://cloud.githubusercontent.com/assets/3209501/9069612/2d70ea8e-3a9f-11e5-864d-87986f7de4e2.png)

**Comment by marimuraki** [comment]
Great @alexsoble! One update. Now that we are not restricted to the 3 buckets of {High, Medium, Low} and since - as Uri said - we want to be consistent with the language already used by teachers / principals / etc, let's include all Risk Levels {0, 1, 2, 3}.

@AmirHadjihabib: What would the colors look like for these 4 Risk Levels?

**Comment by marimuraki** [comment]
@AmirHadjihabib: Here is what the current Risk Level colors are based on Kenya's roster.

![screenshot 2015-08-04 18 21 32](https://cloud.githubusercontent.com/assets/1334815/9074230/bf1749b6-3ad5-11e5-958f-ff80510c3c1c.png)

**Comment by AmirHadjihabib** [comment]
I think we can keep the colors we have. By having levels 1 and 2 be the same green.

**Comment by marimuraki** [comment]
@AmirHadjihabib: Risk Levels 0 & 1. Risk Levels 1 & 2 are not group-able.

We can look into how many students are Risk Level 0 vs. 1 but can you mock-up what it would be like to do different colors (maybe different shades of green like in the original roster) for Risk Levels 0 & 1?

Somerville specifically is using 4 Risk Levels to categorize their students --- otherwise they would be using 3 Risk Levels if they didn't need to differentiate between Levels 0 & 1. So I think it is important to think about it more carefully.

I can follow-up with Uri, Vince and the teachers more specifically.

**Comment by AmirHadjihabib** [comment]
Just in color. The values would still show as 0 and 1. Don't feel we need 2 shades of green.

**Comment by marimuraki** [comment]
@AmirHadjihabib: Sounds good.

**Comment by marimuraki** [comment]
@AmirHadjihabib: Looping back on this again so I understand the design decision. 

A concern I have is that if the user sees the same color, s/he will not easily be able to differentiate the students based on whether they are Risk Level 0 or Risk Level 1 -- when the distinction may be important -- and it might be a source of confusion. 

Can you help me understand why the design decision behind grouping Risk Levels 0 and 1 as the same color?

Intuitively I believe differentiation is important so would love to better understand.

@alexsoble: What do you think?

Thanks!

**Comment by marimuraki** [comment]
DONE: https://github.com/codeforamerica/somerville-teacher-tool/pull/224

**Comment by marimuraki** [comment]
As brought up by Jill, *"why are risk levels N/A?"*

@alexsoble: We need to add in **DIBELS** to the risk level definitions.

- **STRATEGIC**: Risk Level 2
- **INTENSIVE**: Risk Level 3

**Comment by marimuraki** [comment]
Also, in response to, as brought up by Jill, *"why are risk levels N/A?"*, maybe we should include an explanation of why the student's risk is N/A?

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Kenya is working on **new** risk level definitions. We will meet with her on Friday to go over the new criteria for risk.

**Comment by alexsoble** [comment]
Moving this over to #280 so we can start a clean thread about the new risk level formula.
