### ISSUE TITLE
Image spans off on Firefox

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#137]
Issue with how graph image spans out in Firefox. @AmirHadjihabib: can you figure out what is going on here? Similar issue to the CfA report template.

![screenshot 2015-06-23 19 21 20](https://cloud.githubusercontent.com/assets/1334815/8311222/4dc81f9c-19dd-11e5-98ff-16540ba0552a.png)

**Comment by creade** [comment]
Don't know if y'all caught the discussion on slack yesterday about this plaguing all of us but @mapsam had the following suggestion: 

> wrapping all of the images within a `<figure>` with `display:block` seems to do the trick
> 
> seems a big part of the problem is having images wrapped with an `<a>` tag, which is inherently `display:inline`
> 
> FF doesn’t recognize `max-width` on `inline` apparently
> 
> so another quick fix, if you’re going to have full-width images anyways, is to just set `img` to `width: 100%`

**Comment by mapsam** [comment]
@marimuraki is that actually an image or an interactive graphic that is breaking?

**Comment by marimuraki** [comment]
Thanks @creade & @mapsam! ^_^

@mapsam: It's an interactive [chart](http://www.highcharts.com/). 

@AmirHadjihabib: Mind checking out this issue and implementing Sam & Chris' suggestions to see if it fixes it?

**Comment by civerson** [comment]
It looks like the graph is broke, as of last week's refactor to profile.js: Uncaught TypeError: Cannot read property 'split' of null. I'll take a look at what's going on.

**Comment by alexsoble** [comment]
It's a highcharts thing, CSS fix.

**Comment by alexsoble** [comment]
@civerson Hmmm, graph has been working fine at summer school. Please open an issue if you run into that error again. See you tonight at Code for Boston? :blush:

**Comment by civerson** [comment]
It might be something with the seed data. See you tonight.
