### ISSUE TITLE
Don't show assessments that are irrelevant for a homeroom

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#153]
If a homeroom group has no STAR results, don't show STAR in the roster.

If a homeroom group has no STAR results, don't show MCAS in the roster.

**Comment by alexsoble** [comment]
For example, in summer school mode grades 1-3 don't have MCAS results, grade 1 doesn't have MCAS or STAR results

**Comment by marimuraki** [comment]
@alexsoble: MCAS tests grade levels 3-8 and 10.
