### ISSUE TITLE
Figure out which X2 table/column best encodes SPED status

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#156]
`student` column `STD_FIELDB_068`, "ProgramAssigned" looks like a good candidate, but need to better understand range of values:

`{ Sp Ed, Reg Ed, SEIP, 2Way English, 2Way Spanish, Waivered SEIP, Smile, ECIP, Choice, NULL ... }` 

Our current understanding of SPED status the app is as a boolean, `true/false`.

**Comment by marimuraki** [comment]
@alexsoble: On it. Can we pull it into the data exports we are getting from John Breslin?

**Comment by marimuraki** [comment]
Still in works (partial list) ...

- Sp Ed = Special Education
- Reg Ed = Regular Education
- SEIP = Sheltered English Immersion Program
- Waivered SEIP
- [2Way English & 2Way Spanish](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=14489) = *"teaches native speakers of English and Spanish in both languages"*
- [Smile](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=13810) = free preschool program
- ECIP = Early Childhood Intervention Program
- [Choice](http://www.somerville.k12.ma.us/education/components/whatsnew/default.php?sectiondetailid=17731)

@alexsoble: Will add to this list when I have access to the full data. These are for those values listed in the issue.

**Comment by alexsoble** [comment]
So perhaps instead of a SPED column in the roster view we want a Program Assigned column. @marimuraki

**Comment by marimuraki** [comment]
@alexsoble: I'm always for more detail than less. This is a good question to ask the teachers. 

The Program Assigned values include both SPED, ELL and other special programs so may be helpful in the "intervention" piece e.g., do ELL students who are enrolled in 2Way English/Spanish vs. SEIP vs. Reg Ed, etc perform better in ELA/Reading?

**Comment by marimuraki** [comment]
**Update** full list as of 2015-07-07

- [2Way English, 2Way Spanish, 2Way Other](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=14489) teaches native speakers of English and Spanish in both languages
- All English
- Another Lang
- Child Develpmnt
- [Choice](http://www.somerville.k12.ma.us/education/components/whatsnew/default.php?sectiondetailid=17731)
- ECIP = [Early Childhood Intervention Program](http://www.somerville.k12.ma.us/education/components/faq/faq.php?sectiondetailid=18151) is a multi-sensory preschool program that serves both children with special needs and typically developing children
- [Head Start](http://www.caasheadstart.org)
- Low Incidence
- More Lang
- Not Attending
- Reg, Reg Ed = Regular Education
- SEEK, Seek Program = [Social and Educational Enrichment at Kennedy](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=14364) for students with [behavior needs](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=13957)
- SEIP = [Sheltered English Immersion Program](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=14526) is a K-12 program for international students and students who speak other languages than English
- SKIP = [Specialized Kennedy Intensive Program](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=14364) for students with [physical and cognitive needs](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=13957)
- [Smile](http://www.somerville.k12.ma.us/education/components/scrapbook/default.php?sectiondetailid=13810) = free preschool program
- SP Ed, Sp Ed = Special Education
- SP Ed ECIP, Sp Ed ECIP
- Sp Ed LAB
- TBE = [Transitional Bilingual Education](http://www.doe.mass.edu/pqa/review/cpr/reports/2003/0274.pdf)
- Two Way
- Waivered SEIP

@alexsoble

**Comment by alexsoble** [comment]
@marimuraki — Great! Added "ProgramAssigned" to the X2 export via https://github.com/codeforamerica/somerville-teacher-tool/commit/2943bf446c59d2d6f0dc71557cf9e927f5c8a34c.
