### ISSUE TITLE
Fix "Back to Roster" button

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#159]
Uri found issue with the "Back to Roster" button. Clicking it always takes you back to **Grade 7** Roster. 

Example: If you are in the Grade 5 Roster and click on a student for the student profile --- and then click "Back to Roster", it takes you back to the Grade 7 Roster **not** the Grade 5 Roster.

@alexsoble @AmirHadjihabib

**Comment by alexsoble** [comment]
Fixed by @griggsca91 via #167.
