### ISSUE TITLE
Tweak student profile graph

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#160]
Some points in the student profile graph are not connected.

<img width="468" alt="screenshot 2015-07-06 10 14 04" src="https://cloud.githubusercontent.com/assets/1334815/8524211/cc71a59a-23c7-11e5-9315-a66409b3e499.png">

@alexsoble @AmirHadjihabib

**Comment by alexsoble** [comment]
@marimuraki Digging into the data here. These kinds of lines are generated by STAR results with math values but no reading value, for example. The missing reading value is encoded as `nil` which breaks the pretty arc.

**Comment by alexsoble** [comment]
New status: 

![smooth chart](https://cloud.githubusercontent.com/assets/3209501/8531452/7bbc3a4c-23f5-11e5-8afe-1124573b9f40.png)
