### ISSUE TITLE
Feedback from SomerSession Summer School

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#162]
- [x] order of STAR assessments by date in student profile timeline is confusing i.e., out of order
- [x] sequence of STAR assessments should be most recent first
- [ ] no behavior incidents? what behavior incidents does your school record?
- [ ] blue circles is confusing, "didn't like it", "why not red? I'm used to that and I know what I am working with" 
- [ ] why does the student not have MCAS scores?
- [ ] scale in the graphs change
- [x] seeing IEP, SPED, ELL demographics would be helpful

@alexsoble @AmirHadjihabib

**Comment by alexsoble** [comment]
:blush: — Good notes @marimuraki!

**Comment by alexsoble** [comment]
Other bugs fixed via summer school feedback: #160, #161, #163.

**Comment by alexsoble** [comment]
@marimuraki, who do you think we should talk to to answer the question, "what behavior incidents does your school record?"

**Comment by marimuraki** [comment]
@alexsoble: Think what behavior records are collecting might be a school-specific policy or at discretion of the teacher? Let us ask Vince about what the district policy is for recording behavior incidents.

**Comment by marimuraki** [comment]
@alexsoble: Asked Vince about behavior records. He has cc'ed the Director of Student Services, Richard Melillo.

**Comment by marimuraki** [comment]
**Feedback from Uri**

- [ ] Getting ACCESS (ELL) scores in there and pulled from X2
- [ ] Getting DIBELS scores in there and pulled from X2
- [ ] Printable version of the student profile (PDF) that puts all the info into a page or two for use in student support/SPED referral
- [ ] Include risk levels in there that Kenya uses in the rosters - people have gotten very used to seeing those
- [ ] In student profile, seeing a student's ELL, 504, and SPED status
- [ ] A school view, so that an administrator can look at the school and sort to see who are the top students in need, whether they sort by attendance, risk level, behavioral incidents, low MCAS growth - that way they have an ongoing view of the neediest students to use in their student support team meetings or child study

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
**Consolidated feedback from teachers -- grades 3, 4, 5, 7, 8** 

**Roster**
- [ ] add column with risk levels

**Graphs**
- [ ] consistent scale on graphs e.g., [min, max] scores
- [ ] click from roster to specific graph (not directly to attendance)

**Profile**
- [x] order of STAR assessments by date in student profile timeline is confusing i.e., out of order
- [x] sequence of STAR assessments should be most recent first
- [ ] group STAR assessments by semester e.g., Fall, Winter, Spring rather than by specific date

**Design**
- [ ] change colors: blue circles is confusing, "didn't like it", "why not red? I'm used to that and I know what I am working with" @AmirHadjihabib 

**Data**
- [ ] missing MCAS scores
- [ ] behavior incident data collection
- [ ] IEP/SPED & ELL demographics on student profile & in roster
- [ ] DIBELS
- [ ] ACCESS
- [ ] add afterschool programming information

**Additional Features**
- [ ] commenting
- [ ] interventions
- [ ] IEP process
- [ ] export & print to 1 page

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
**Mockups done for:** 

**Priorities** tagged with :star: 
**Feedback count** tagged with :+1 (above 1 vote): 

**Roster**
- [x] add column with risk levels

**Graphs**
- [x] see when intervention started / ended with the performance to see progress

**Profile**
- [x] order of STAR assessments by date in student profile timeline is confusing i.e., out of order
- [x] sequence of STAR assessments should be most recent first
- [x] group STAR assessments by semester e.g., Fall, Winter, Spring rather than by specific date

**Design**
- [x] change colors of warning circles

**Data**
- [x] IEP/SPED & ELL demographics on student profile & in roster :star: :+1: :+1:
- [x] DIBELS :star: :+1:
- [x] ACCESS 

**Additional Features**
- [x] commenting :+1: 
- [x] interventions :+1: 
- [x] export & print to 1 page :star: :+1: :+1: 

@alexsoble @AmirHadjihabib https://projects.invisionapp.com/share/ZA3KC8FGN

**Comment by marimuraki** [comment]
Implementation done for adding colored risk level to roster and profile: #183

**Comment by marimuraki** [comment]
**Consolidated feedback from teachers -- grades 3, 4, 5, 7, 8** + Updated with feedback from Sarah (Efrem's wife)

**Priorities** tagged with :star: 
**Feedback count** tagged with :+1 (above 1 vote): 

**Roster**
- [x] add column with risk levels
- [ ] add explanations of risk levels e.g., how were the risk levels computed?
- [ ] remove H, M, L ... just colored circles? @AmirHadjihabib 
- [ ] change color of warning circles to un-filled red circle outline? @AmirHadjihabib 
- [ ] show SPED info as default in roster

**Graphs**
- [ ] consistent scale on graphs e.g., [min, max] scores :star:
- [ ] click from roster to specific graph (not directly to attendance) :star:
- [ ] see when intervention started / ended with the performance to see progress
- [ ] see attendance and performance in one graph to see any relationship :+1: or create a dashboard of multiple graphs #119

**Profile**
- [x] order of STAR assessments by date in student profile timeline is confusing i.e., out of order
- [x] sequence of STAR assessments should be most recent first
- [ ] group STAR assessments by semester e.g., Fall, Winter, Spring rather than by specific date

**Design**
- [ ] change colors: blue circles is confusing, "what does blue mean?". "didn't like it", "why not red? I'm used to that and I know what I am working with" @AmirHadjihabib :star: :+1: :+1:

**Data**
- [x] IEP/SPED & ELL demographics on student profile & in roster :star: :+1: :+1:
- [ ] DIBELS :star: :+1:
- [ ] ACCESS 
- [ ] Fountas & Pinnell
- [ ] missing MCAS scores :+1:
- [ ] behavior incident data collection (how? what?) :+1: 
- [ ] add afterschool programming information

**Additional Features**
- [ ] commenting :+1: 
- [ ] interventions :+1: 
- [ ] IEP process :+1: :+1: 
- [x] export to CSV :star: :+1: :+1: 
- [ ] print to 1 page :star: :+1: :+1: 

@alexsoble @AmirHadjihabib
