### ISSUE TITLE
Tweak student profile timeline

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#163]
Feedback on timeline. Let's discuss @alexsoble @AmirHadjihabib

The school year timeline goes from **new to old** but within a school year, the assessment timeline goes reverses **old to new**. Both teacher groups that we observed / interviewed were confused. They expected to see the newer scores on the top. They specifically requested that the STAR timeline within the school year be reversed starting from most recent.

Let's keep an eye out and see if other teachers have similar or different responses to the timeline.

**Comment by marimuraki** [comment]
@AmirHadjihabib: In timeline, when data is missing, need some missing state. Currently it is blank and messes up the formatting.

<img width="489" alt="screenshot 2015-07-06 10 00 53" src="https://cloud.githubusercontent.com/assets/1334815/8523906/f782723e-23c5-11e5-905d-c6d7967b802d.png">

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib 

BUG: STAR results in student profile timeline are not in sequential order.

**Example:**

- February 25 2015
- June 8 2015
- September 18 2014
- June 10 2015

**Comment by marimuraki** [comment]
Fixed by @alexsoble! YAY!

**Comment by alexsoble** [comment]
Re-opening to fix the missing state for STAR results.

**Comment by alexsoble** [comment]
Not the prettiest, but indicates a missing value:

![star results box](https://cloud.githubusercontent.com/assets/3209501/8528343/856b91c4-23e0-11e5-8a71-b406fdca81bc.png)
