### ISSUE TITLE
Fix Student Insights logo

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#165]
The current image is being cropped. Exported new files. PNG and SVG

https://www.dropbox.com/sh/kbb8p69e2x6rrdv/AADhRro-lGG7UiTOMXPngrXpa?dl=0

**Comment by marimuraki** [comment]
@AmirHadjihabib: Has this been updated in production?

**Comment by marimuraki** [comment]
@AmirHadjihabib: is this issue closed?
