### ISSUE TITLE
Create a school view for administrators

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#169]
**Feedback from Uri**

- *A school view, so that an administrator can look at the school and sort to see who are the top students in need, whether they sort by attendance, risk level, behavioral incidents, low MCAS growth - that way they have an ongoing view of the neediest students to use in their student support team meetings or child study*

**Comment by marimuraki** [comment]
**Feedback from Principals**

- **What views of the data would be useful to see as a principal?**
  - *"grade-level views of Roster would be useful"*
  - like the Roster >> Profile but at grade-level / school-level
  - Would be helpful to have a summary on top with basic aggregate numbers e.g., X number of students in Grade G are Risk 3, etc ...
    - lots of numbers to look through especially with large classrooms or at grade-level or at school-level
    - *"Is there a way to include a summary box on top that makes all this data more digestible --- rather than having to sort & scroll down the table to, say, count up how many high risk students are in a grade level and how many of these high risk students are ELL, etc?"*
    - look at data by subgroup
      - e.g., *"how do ELLs in this classroom compare to non-ELLs in this classroom?"*
- **What other information would be useful to see as a principal or a teacher?**
  - Homeless status
  - Student address
  - IEP data
  - MTSS referral
    - *"Has the student been referred to MTSS?"*
  - School-level aggregate measures
    - *"Could you include school measures? What else can you be measuring about kids that can show us the deficits?"*
- **How do you use student data?**
  - *"As sort of a case manager, I track the progress of a certain subgroup. My job is to see how they are doing, what has been tried, what has worked, what has not worked. Intervention view is important."*
    - Who does this? Principals, teachers, student support, etc.
  - *"For the certain number of students in warning / at risk, I want to be able to pull that group of students and see what all of their interventions have been — I want to see patterns."*
  - "For the struggling students, I want to see if there are shared patterns in attendance, discipline, and interventions."*
- **How do you imagine using the tool?**
  - "I would use it daily" - Kathleen
  - Classroom observations
    - *"If I go to classroom for observations, I would be able to pull up the classroom and see information on individual students"*
  - Answer questions
    - *"Why is one student making progress and another is not?"*
    - *"May lead to certain questions you have not asked yet"*
- **Other features & comments**
  - Graph of risk levels
    - *"Can you include a graph of the risk levels over time?"*
  - Graphs of assessments
    - *"Is there a way to compare assessment test over time in one graph — by levels?"*
  - Benchmark line on graph
    - Put line for typical growth at 50th percentile or range between 40th - 60th percentile
    - Don't want parents or teachers to think that anything above a 40th percentile is good.
  - PDF reports
    - *"I've used reports like this in meetings"*
    - Include date of report
    - Add DIBELS & ACCESS
    - Add behavior & interventions
    - *"I like to see attendance on same side as growth"*
    - *"Can you choose what goes where in report?"*
  - Data export
    - *"Can you export the Roster for the whole class, whole school?"*
    - *"As a teacher I would want to export all my student's data, not each student's data one at a time and have to compile 25 student files"*
  - Timeline
    - Lots of scrolling to see information.
    - Want it to be more compact so I can see more information.

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
@AmirHadjihabib: Uri mentioned this today at our post-SST meeting. Do you have an idea of when you will be able to provide Uri with a design of an admin view?

Not high priority but wanted to ping this on your radar for later.

**Comment by marimuraki** [comment]
Example student dashboard from Code for Boston: http://www.perceptualedge.com/files/studentDashboard/

**Comment by marimuraki** [comment]
@alexsoble: Read my notes from my last meeting with Jill about the principal dashboard. Includes specifics along the lines of what was discussed today.

**Comment by marimuraki** [comment]
Questions to ask principals (feedback from @alexsoble & Code for Boston):

- What makes a good (bad) day?
- What has "bitten" you in the past?
- What do you spend the most (too much) time on?
- What can you not do now that you want to be able to do?

**Comment by alexsoble** [comment]
@kevinrobinson shipped this the other day. 

:+1: :rainbow: :+1:
