### ISSUE TITLE
Don't show attendance first

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#176]
One of the pieces of feedback from SomerSession pilot teacher Steve was that attendance shows up first in all of UIs on the student profile page — the charts, the school year boxes. But attendance isn't the first metric he wants to see as a teacher. Move attendance down the hierarchy show that STAR shows up first instead.

Part of #162.

**Comment by alexsoble** [comment]
@marimuraki @AmirHadjihabib:

Do we want the chart on the profile page to show STAR by default? MCAS scores? MCAS growth? 

A few thoughts for each:

+ __STAR__: Timely! But a newer assessment, we've heard some teachers say they're not sure how much weight they want to put in it right now.
+ __MCAS scores__: Less timely (1x year) but teachers are very familiar.
+ __MCAS growth__: Same as above.

Thoughts?

**Comment by marimuraki** [comment]
@alexsoble: I agree. Many of the teachers seemed to either 1) not understand STAR or 2) not think it as reliable. Still I am torn because STAR is a more frequent assessment of student performance --- compared to MCAS which is only once a year. Think this is something to ask the teachers.

**Comment by marimuraki** [comment]
@alexsoble: I'll include this as a question to ask Sam when I meet with her next week.

**Comment by marimuraki** [comment]
I think this is resolved by the roster to profile click-through. Commit: https://github.com/codeforamerica/somerville-teacher-tool/commit/7555a94e7c5995236091ec81df2aaa691103c85c
