### ISSUE TITLE
Define Fall, Winter, Spring in school year

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#177]
@AmirHadjihabib reminded us that we need to define Fall, Winter, Spring for our **STAR** and **DIBELS** (possibly other) assessment based on the date taken.

We can do this naively or we can do it based on each year's school calendar.

@alexsoble: What do you think?

**Comment by alexsoble** [comment]
I think this is a good idea but relatively low-priority.

**Comment by AmirHadjihabib** [comment]
I think it's a high to medium priority for users. Not sure on the technical
scale. It did create a fair amount of confusion for the teachers.

On Friday, July 17, 2015, Alex Soble <notifications@github.com> wrote:

> I think this is a good idea but relatively low-priority.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/somerville-teacher-tool/issues/177#issuecomment-122276358>
> .
>


-- 
http://hadjihabib.com/

https://hadjihabib.exposure.so/ <http://vimeo.com/user5513343>

"Imagination is more important than knowledge..."
-Albert Einstein

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Let's discuss priorities again once we are back together next week. 

Updating the {Fall, Winter, Spring} to Quarters based on Somerville Public Schools [calendar](http://www.somerville.k12.ma.us/education/components/docmgr/default.php?sectiondetailid=19179):

**[2015-16 School Calendar](http://www.somerville.k12.ma.us/education/page/download.php?fileinfo=RklOQUxfMjAxNTIwMTZfQXBwcm92ZWRfU2Nob29sX0NhbGVuZGFyX2FtZW5kZWRfMDcwMTE1LnBkZjo6Oi93d3cvc2Nob29scy9zYy9yZW1vdGUvaW1hZ2VzL2RvY21nci8yNjgzZmlsZTE0ODU4LnBkZg==&sectiondetailid=19179)**
- 1st Quarter: 9/2-11/9 (45 days)
- 2nd Quarter: 11/10-1/26 (45 days)
- 3rd Quarter: 1/27-4/6 (45 days)
- 4th Quarter: 4/7-6/16 (45 days)

These dates will change each year.
