### ISSUE TITLE
Add usage analytics

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#178]
What would we want to capture in Google Analytics? - @AmirHadjihabib via Matt Loveless

**Comment by marimuraki** [comment]
@AmirHadjihabib: What is the status of this? Can you remind me what the next steps for this are?

**Comment by alexsoble** [comment]
We're on it, @kevinrobinson is adding in Mixpanel now. :)

**Comment by kevinrobinson** [comment]
@alexsoble This is addressed in https://github.com/codeforamerica/somerville-teacher-tool/pull/419, and I just invited you to the project.

**Comment by alexsoble** [comment]
@kevinrobinson: Pushed to production, here's our first user login event:

![mixpanel](https://cloud.githubusercontent.com/assets/3209501/12730585/9c5529da-c8fa-11e5-84b2-992191c13ef9.png)

:blush: :chart_with_upwards_trend: :blush: :+1:

**Comment by kevinrobinson** [comment]
sweet!
