### ISSUE TITLE
Scope user access by role

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#179]
User groups we have discussed and heard from include:

- **Teachers**: Teachers can see their own classroom or grade level.
- **District Administrators**: District administrators such as Vince and Uri can see all students.
- **School Administrators**: School administrators such as principals and APs can see all students in their school.
- **Student Support**: Student support staff such as reading tutors can see students they are assigned to.
- **Parents**: Parents can see only their child.
- **Students**: Students can see only their own information.

@alexsoble @AmirHadjihabib: Any other user groups?

**Comment by alexsoble** [comment]
Figuring out how to do this with the data we have from X2: #388 

If X2 data can't get this done for us we may need to build admin dashboard for principals to set permissions.

**Comment by alexsoble** [comment]
Closed via:

+ #438
+ #442
