### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#18]
Key areas to cover with tests: 

1. __Data access:__  Authorized users can access data on the site; unauthorized users can't. 
2. __Data quality:__  Data can be imported without quality loss.

**Comment by hunterowens** [comment]
We should talk about how to test School data- I've got some thoughts about what I've done that doesn't work, would like to hear what you think.

**Comment by alexsoble** [comment]
@hunterowens That sounds like a great conversation. I'm in Chicago this Thursday through Sunday for Do Good Data, and then again May 11—15. We should get together in person if you're still in Chi.

**Comment by hunterowens** [comment]
Still here, let's do it.

**Comment by alexsoble** [comment]
ToDo:

+ [ ] Feature tests for roster column sorting
+ [ ] Feature tests for profile charts

**Comment by alexsoble** [comment]
More of an ongoing process than a separate issue, should be part of every PR.
