### ISSUE TITLE
Student Insights V2

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#180]
##### Description:
The second iteration of Student Insights based on feedback from the Somerville summer school teachers. How might we build on what we currently have to better fit their needs?

##### User story:
Roster
* As a teacher, I want to see at a glance which students belong to which Risk Levels so I can have a clear picture of all my students' needs.
* As a teacher, I want to see how many interventions a student has received so I can understand whether the students has been receiving supports.

Profile
* As a teacher, I want to view detailed demographics and educational information for a student so I can better understand that student.
* As a teacher, I want to be able to export the Profile of a student so I can use it to communicate that student's needs to others(parents and staff).
* As a teacher, I want to view the student's guardians contact information so I can connect with the family.
* As a teacher, I want to view a more detailed assessment history for a student so I can have a better picture of their progress.
* As a teacher and a support staff, I want to record interventions by student and date so I can keep a history of a student's interventions.
* As a teacher and a support staff, I want to see the interventions alongside student performance / behavior so that I can better understand whether interventions are effective. 
* As a teacher, I want to keep a log of comments so that I can share information with others.

##### Student Insights V2:
Roster
* [x] I see Risk Level by student
* [x] I see Risk Level as the default sort(High to Low)
* [x] I can sort by Risk Level
* [ ] I see intervention counts by student

Profile
* [x] I see the student's demographics and educational information
* [ ] I can export the Profile as a PDF
* [x] I can export the Profile as a CSV
* [ ] I see the student's guardians contact information 
* [ ] I see the student's early ed information(DIBELS)
* [ ] I see the ELL student's language progress(ACCESS)
* [ ] I can add intervention, type, end date, and comment
* [ ] I see the intervention time period overlaid on student profile graphs
* [ ] I can add comments to the Profile

##### Design:
Roster:
http://invis.io/UM3M7Z7K3

Profile:
http://invis.io/ZA3KC8FGN

![roster - home](https://cloud.githubusercontent.com/assets/4615904/8806007/46079e42-2f89-11e5-8a3e-94375289302c.png)

![profile - landing](https://cloud.githubusercontent.com/assets/4615904/8806006/46076c4c-2f89-11e5-9042-ed93d67497af.png)

**Comment by AmirHadjihabib** [comment]
##### Student Insights V2 - Priority list
A working list of new features to be built into V2 of Student Insights. Based on the designs V2 designs.
[Priority list](https://docs.google.com/document/d/1_l3NCXTsvQoTuX-DG0pd9QcAAyMwJfncJqk-oa_liFU/edit?usp=sharing)

**Comment by marimuraki** [comment]
Uri's Priority List

- #1 Getting the risk levels in there that Kenya uses in the rosters - people have gotten very used to seeing those
- #2 Getting ACCESS (ELL) scores in there and pulled from X2; same for DIBELS
- #3 A Printable version of the student profile (PDF) that puts all the info into a page or two for use in student support/SPED referral
- #4 In the student profile, seeing a student's ELL, 504, and SPED status
- #5 A school view, so that an administrator can look at the school and sort to see who are the top students in need, whether they sort by attendance, risk level, behavioral incidents, low MCAS growth - that way they have an ongoing view of the neediest students to use in their student support team meetings or child study

**Comment by AmirHadjihabib** [comment]
Here is the PDF export design

https://www.dropbox.com/s/4w3tkxq8rflaznf/profile_export.pdf?dl=0

![profile_export](https://cloud.githubusercontent.com/assets/4615904/8991086/25deb410-36ab-11e5-91ff-7ea52df4fecb.png)

**Comment by marimuraki** [comment]
:+1: #72

We can say that the prioritization of PDF one-pager in terms of assessments is MCAS and STAR. We may need to differentiate for higher and lower grades though. For lower grades, they will not have MCAS (starts in grade 3) and will have DIBELS instead.

@alexsoble @AmirHadjihabib: I'll show Sam this mock-up and get her feedback.

**Comment by marimuraki** [comment]
@AmirHadjihabib: **Comment on profile timeline**

- **Too much scrolling.** Profile timeline takes too much scrolling to see information. Information is too spread out. A student's information cannot be easily seen in one snapshot - either over multiple years or even for just one school year.

**Comment by marimuraki** [comment]
@AmirHadjihabib @alexsoble: We heard from both teachers and now Uri how SPED & disability information is key. Let's include it as default on roster view.

*"SPED shown as default would be great. In terms of priority, disability, level of need and 504 plan. Placement takes up a lot of space and teachers probably know this already so you can drop this from default so it's not so busy."* - Uri

**Comment by marimuraki** [comment]
@AmirHadjihabib: Can you change the Warning Indicators hover text to say:

**MCAS Growth**: Below the 40th percentile
**STAR Percentile**: Below the 40th percentile

The principals today reminded me that "percentile" is the correct terminology. "Points" is not accurate.

<img width="370" alt="screenshot 2015-08-04 17 12 40" src="https://cloud.githubusercontent.com/assets/1334815/9072949/34a020f4-3acc-11e5-89e6-d2b0260d55ea.png">

@alexsoble

**Comment by AmirHadjihabib** [comment]
##### Intervention list
* X-Block
* Teaching plan
* Phone call
* Reading tutor
* Add custom intervention(TBD)

**Comment by marimuraki** [comment]
Reviewed the priorities with @AmirHadjihabib. Most done!

Remaining issues:
- interventions
- commenting
- export
- print

**Comment by marimuraki** [comment]
@AmirHadjihabib: Closing this as you work on V3.
