### ISSUE TITLE
Add alert to notify new key assessment data available

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#190]
From conversation with Matt Loveless:

- alert teachers when key new data is out e.g., MCAS, STAR, DIBELS, ACCESS, etc

**What might this address?**

Given that the information is not significantly changing day to day, teachers may stop using the tool if each time they log in they don't see anything new i.e., useful. By alerting them when new data is available, they will interact with the tool when it is most useful i.e., has new data to look at.

**Teacher Feedback**

Sam has mentioned how she pings Uri about the new assessment data is available. 

@AmirHadjihabib @alexsoble

**Comment by alexsoble** [comment]
This would be a neat feature but low on the list of top priorities, closing for now.
