### ISSUE TITLE
Unified assessment model

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#192]
Having separate models for each kind of assessment is no good.

Let's build a unified model.

Pairing with @marimuraki!

**Comment by marimuraki** [comment]
:heart: thank you @alexsoble for pairing with me & showing me more about tests, specs, etc. It was fun! :blush:

**Comment by marimuraki** [comment]
@alexsoble: Here are the assessments from X2. Starred :star: are the assessments we should pull in the assessment model.

- ACCESS :star:
- WIDA-ACCESS :star: (same as ACCESS, simply named differently in X2 for earlier years)
- MELA-O :star: (replaced by ACCESS)
- MEPA :star: (replaced by ACCESS)
- DIBELS :star:
- MCAS :star:
- MAP :star: (replaced by STAR)
- STAR (currently pulling in from STAR export)
- CTBS
- GRADE
- IDEA
- IPT
- Pre-IPT
- SABE
- SATI
- SATII
- W-APT

**Comment by alexsoble** [comment]
@marimuraki — Makes sense! Until we write a whitelist for `X2AssessmentImporter` it is going to import all of them.
