### ISSUE TITLE
Integrate MAP data

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#194]
MAP is the assessment that was replaced by STAR. We have at least 5 years of MAPS assessment we should pull in for the student assessment history.

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
Let's pull in MAP assessment. Why?

- provides history of assessment before MAP was replaced by STAR
- is current assessment used by KIPP NJ

**Comment by marimuraki** [comment]
Comments on MAP from Vince, Kenya & principals meeting.

**Mixed feedback**
- *"Would not include MAP"* - Kenya
- *"Did not find MAP that useful"* - Kathleen
- *"Would be good to see full assessment history of kids"* - Vince
- *"Only if you can match up grade level equivalence"* - Vince
- *"How about adding a link to MAP data but not show it in tool?"* - Jill
- *"Or show only raw score - and put conversion chart nearby"* - Vince
- *"Conversion chart is a pain"* - Vince

@alexsoble @AmirHadjihabib

**Comment by alexsoble** [comment]
@marimuraki — Helpful to sketch out what MAP would look like in the roster / profile because KIPP NJ uses MAP.

**Comment by marimuraki** [comment]
Yes, @alexsoble: doing that now.

**Comment by marimuraki** [comment]
In Somerville's X2, we have MAP scores and growth data but no performance level values:

- `assessment_scale_score`
- `assessment_growth`
- `assessment_performance_level` (all null values)

@alexsoble @hunterowens: Based on the fake KIPP NJ MAP data, it seems they have performance level data. Somerville does not have it in X2. Do we want to include performance levels --- or just scores?

Based on the discussion with Somerville, seems if MAP is included, they did not find MAP a reliable assessment and if included in the tool, would only want to see raw scores.

**Comment by almartin82** [comment]
Hi! Andrew from KIPP NJ here. Most valuable would be to have the percentile rank for the student's most recent assessment; second most important would be the raw RIT score

**Comment by almartin82** [comment]
@alexsoble I have tabular RIT to percentile lookups handy, if you want them

**Comment by almartin82** [comment]
very curious what they mean by conversion chart.

**Comment by hunterowens** [comment]
Pretty sure that conversion chart is basically a lookup table between two exams.

**Comment by marimuraki** [comment]
@almartin82: Yes, that would be helpful. Can you provide a data dictionary or other documentation on the MAP data e.g., key assessment measures, value types, [min, max] or values e.g., level categories where relevant.

Been referring to https://www.nwea.org/assessments/map/ but not that easy to navigate to find information. If you can provide a better reference, that would be great!

**Comment by marimuraki** [comment]
@almartin82 @hunterowens @alexsoble: Yes, the conversion chart the Asst. Superintendent and principals were referring to is the conversion to be able to compare MAP to STAR.

**Comment by alexsoble** [comment]
@almartin82 @marimuraki @hunterowens — Want to make sure we're using the same terminology for talking about assessment scores. Our assessment model knows about the following kinds of results at the moment:

* `scale_score`
* `growth_percentile`
* `performance_level`
* `percentile_rank`
* `instructional_reading_level`

Does KIPP NJ's MAP data map neatly onto these categories? We've got `percentile_rank`, and it looks like RIT is a measure of growth. Do you think the attributes above can model the MAP results well, or should we add more?

We can hop on the :phone: to discuss if that's easier.

**Comment by alexsoble** [comment]
Prioritizing :arrow_up: on data quality for MCAS and STAR, then making DIBELS and ACCESS first-class citizens. MAP should be in the queue but not for this current iteration.
