### ISSUE TITLE
Print out student profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#233]
Pulling this out from https://github.com/codeforamerica/somerville-teacher-tool/issues/72

@AmirHadjihabib @alexsoble: Comments from Uri on PDF print-out of student profile

Uri liked the one-page printout but said that key information on behavior and interventions is missing.

- Use case: His vision of how the PDF will be used is in MTSS (multi-tiered system of support) school support team meetings, parent-teacher conferences, and SPED student referrals. For all these meetings, behavior and interventions are key.
- Feedback: Uri said if it takes a 2-page PDF to include all key information, it's ok and it can be printed double-sided. But more important than the number of pages is having the information that is needed to make student support / referral / etc decisions.

Amir's design: Also see #180

https://www.dropbox.com/s/4w3tkxq8rflaznf/profile_export.pdf?dl=0

**Comment by marimuraki** [comment]
@AmirHadjihabib: Can you mock up what the print-out would look like with the behavior and other key data?

**Comment by alexsoble** [comment]
Tracking this in #100.
