### ISSUE TITLE
Build in interventions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#234]
Build in interventions.

- add interventions in profile
- multi-select and add interventions for multiple students from roster
- highlighting intervention periods

Vince, Uri, principals and teachers all love the highlighting of intervention periods in the profile graphs.

Refer to #162, #180

**Comment by alexsoble** [comment]
A few things for us to think about: 

* The start date / end date format doesn't make sense for all the intervention types we have listed. For example, "Phone Call" doesn't have a separate start date and end date. https://github.com/codeforamerica/somerville-teacher-tool/issues/180#issuecomment-128457697

* We are currently aggregating attendance events up to the school year level. If an intervention starts in September and ends in March, how do we want to show that on the attendance events chart? As a fraction of a school year?

**Comment by alexsoble** [comment]
More edge cases we should think about: 

* How X- and Y-axis bands should play nicely together: 

![z indexes](https://cloud.githubusercontent.com/assets/3209501/9293839/f0de7b64-43ee-11e5-9cb6-08083296c748.png)

* How to style shorter interventions:
![shorter intervention](https://cloud.githubusercontent.com/assets/3209501/9293841/0ab273a6-43ef-11e5-9989-51f5c1ae206d.png)

**Comment by marimuraki** [comment]
Nice & good points @alexsoble :+1: 

Another question from principals was what happens when the interventions over lap for a period of time, say, math tutor from Jan-March and reading tutor from Feb-Apr?

After discussing this, the principals agreed with simply showing that intervention together for the combined period of Jan-Apr with a hover that has a brief description of what interventions occurred ... then going down to the interventions section for more details. So let's:

- remove the static label
- include a hover

@AmirHadjihabib: Thoughts in particularly on:

- How y-axis, plotband labels, and intervention bands play nice?
- How to represent one-day interventions?

**Comment by marimuraki** [comment]
@AmirHadjihabib: Can you mock up the multi-select from roster to interventions in profile? Low priority.

**Comment by marimuraki** [comment]
Pair w/ @AmirHadjihabib on intervention bands:

- [x] increase transparency to play well with axis and plotband labels
- [x] remove intervention label
- [ ] include hover (later)

**Comment by AmirHadjihabib** [comment]
![screen shot 2015-08-20 at 11 52 49 am](https://cloud.githubusercontent.com/assets/4615904/9392549/4f0e96e2-4732-11e5-903f-16a724de26d4.png)

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Here are the interventions provided by Uri.

- After School Tutoring (ATP)
- Attendance Officer
- In-House Counseling
- Attendance Contract
- Behavior Contract
- Behavior Plan
- Before School Tutoring
- Boys & Girls Club
- Community Schools
- Outside Counseling/Physician Referral
- Peer Mediation
- Reading Teacher
- Weekly Call/Email Home
- X Block Tutor
- 51a Filing
- Other

**Comment by marimuraki** [comment]
<img width="875" alt="screen shot 2015-09-28 at 11 00 42 am" src="https://cloud.githubusercontent.com/assets/1334815/10144044/3ef79c7e-65d0-11e5-873c-e88355dda9fd.png">
