### ISSUE TITLE
Tweak profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#239]
We heard feedback that the profile timeline requires a lot of scrolling, is spread out too much, lots of empty space, etc.

@AmirHadjihabib: Can you think of how we might refine the profile timeline to reduce the swaths of empty space?

<img width="999" alt="screenshot 2015-08-13 20 43 53" src="https://cloud.githubusercontent.com/assets/1334815/9266952/dba0c98a-41fc-11e5-8e7d-2cfdff4c624f.png">

**Comment by marimuraki** [comment]
Actually the white space issue might largely be an issue when the profile is not zoomed in at 100%.

Here is what it looked at 100%:

<img width="1052" alt="screenshot 2015-08-13 20 52 53" src="https://cloud.githubusercontent.com/assets/1334815/9266986/5bcbd1ea-41fd-11e5-8dd6-2f36afadffc5.png">

*Vertical* scrolling is still a design question to think about @AmirHadjihabib. Teachers want to be able to compare information between years. While they can do that in the graphs, when trying to do so in the timeline, they have to scroll back and forth, back and forth quite a bit. Ideas?

**Comment by marimuraki** [comment]
@AmirHadjihabib @alexsoble: Let's add a null-case for DIBELS and ACCESS. 

Here's an example of what a null DIBELS case looks like. We should add text similar to Attendance and Behavior.

<img width="447" alt="screenshot 2015-08-17 14 19 40" src="https://cloud.githubusercontent.com/assets/1334815/9316657/29f4d536-44eb-11e5-943e-4a50aff9beb4.png">

**Comment by marimuraki** [comment]
@AmirHadjihabib @alexsoble: I am working on this null case.

**Comment by marimuraki** [comment]
<img width="450" alt="screenshot 2015-08-17 18 10 30" src="https://cloud.githubusercontent.com/assets/1334815/9320171/a6f83940-450b-11e5-8914-47b9980cb691.png">

**Comment by marimuraki** [comment]
Also @alexsoble @AmirHadjihabib: Let's include dashes "-" for missing values rather than blanks.

<img width="580" alt="screenshot 2015-08-18 11 14 37" src="https://cloud.githubusercontent.com/assets/1334815/9338648/a0baa42a-459a-11e5-95c3-525369cbcca4.png">

**Comment by marimuraki** [comment]
Updating null cases for ACCESS.

**ACCESS**

**Before**
![screenshot 2015-08-19 11 23 43](https://cloud.githubusercontent.com/assets/1334815/9365180/03896238-4665-11e5-9151-f73f2c5a21d3.png)

**Now**
![screenshot 2015-08-19 11 24 15](https://cloud.githubusercontent.com/assets/1334815/9365176/fadd36be-4664-11e5-8049-aa8ca73b9278.png)

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
Updating view of null cases for MCAS.

**Before**
![screenshot 2015-08-19 11 22 36](https://cloud.githubusercontent.com/assets/1334815/9365211/360b01e4-4665-11e5-8d0a-aae847c54ca1.png)

**Now**
![screenshot 2015-08-19 11 23 07](https://cloud.githubusercontent.com/assets/1334815/9365212/37bdd278-4665-11e5-9878-56aaef04c0aa.png)

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Currently there is no risk level explanation for Risk Level 0.

![screenshot 2015-08-19 13 12 33](https://cloud.githubusercontent.com/assets/1334815/9367740/2dc2b3d8-4674-11e5-84a2-215f85506069.png)

**Comment by marimuraki** [comment]
Actually @alexsoble @AmirHadjihabib: Not showing for any of the risk levels.

![screenshot 2015-08-19 13 18 02](https://cloud.githubusercontent.com/assets/1334815/9367845/ca905170-4674-11e5-88a5-814f77ca7336.png)

**Comment by alexsoble** [comment]
@marimuraki — Love the null case handling work!

**Comment by alexsoble** [comment]
@marimuraki — Risk level explanations missing is a known issue, will fix with #245.

**Comment by marimuraki** [comment]
**ACCESS**

Rather than show "-" when all missing, we should probably just not include that assessment block.

![screenshot 2015-08-19 14 14 53](https://cloud.githubusercontent.com/assets/1334815/9369232/b4c42aee-467c-11e5-8cdd-7820134489d3.png)

**Comment by marimuraki** [comment]
**DATE of ASSESSMENT**

@alexsoble @AmirHadjihabib: We should be consistent with including (or not) the date of the assessment.

Here is an example of how it is now --- where we show the date of assessment only for DIBELS and not for the other assessments listed.

![screenshot 2015-08-19 14 29 22](https://cloud.githubusercontent.com/assets/1334815/9369551/cdf29daa-467e-11e5-9aae-b16f6331a609.png)

**Comment by marimuraki** [comment]
Thinking more, I don't think the specific date is relevant for DIBELS, MCAS, ACCESS (unlike STAR) as they are taken at specific scheduled times in the school year --- not particularly relevant information. I vaguely remember the teachers saying such as well.

**Comment by marimuraki** [comment]
![screenshot 2015-08-19 14 47 11](https://cloud.githubusercontent.com/assets/1334815/9369896/33beebb4-4681-11e5-9404-dcbf27e3fe53.png)

**Comment by marimuraki** [comment]
@AmirHadjihabib: Can you think of how we can address the **lots of scrolling** feedback?
