### ISSUE TITLE
Tweak roster: colors & columns

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#240]
We received feedback from teachers to separate out the math and ELA/reading results in the roster. Now both subjects are paired together under the assessments: MCAS & STAR.

![screenshot 2015-08-14 17 38 19](https://cloud.githubusercontent.com/assets/1334815/9286585/5d1ca93a-42ab-11e5-8da2-c863712d8096.png)

**Why is this useful?**
- teachers want the flexible to see specific subjects e.g., see STAR math next to MCAS math (not show the ELA/reading columns in between)
- in upper grades, teachers are departmentalized e.g., Math teacher not particular interested in seeing ELA scores by default

@alexsoble: @AmirHadjihabib's earlier version had a breakout by subject.

**Comment by marimuraki** [comment]
Also, replace "N/A" with "-" to make it visually cleaner.

<img width="494" alt="screenshot 2015-08-17 18 09 44" src="https://cloud.githubusercontent.com/assets/1334815/9320185/c95da89e-450b-11e5-9902-c4300b9e5386.png">

**Comment by marimuraki** [comment]
<img width="492" alt="screenshot 2015-08-17 18 10 02" src="https://cloud.githubusercontent.com/assets/1334815/9364038/0546ddcc-465f-11e5-953e-76659c78035a.png">

**Comment by marimuraki** [comment]
@AmirHadjihabib: Let's fix:

- color for light green risk level 0 (hard to differentiate with dark green according to Alex)

Let's add new:
- mock up what a summary box of roster

**Comment by marimuraki** [comment]
@AmirHadjihabib: We checked off (mostly) these two issues!

- friendlier colors
- summary box

:smile: 

Screenshots, por favor!

**Comment by AmirHadjihabib** [comment]
![screen shot 2015-08-21 at 3 28 54 pm](https://cloud.githubusercontent.com/assets/4615904/9420338/602cc8ee-4819-11e5-9acc-5d19a2a0c376.png)

**Comment by marimuraki** [comment]
:heart: glad we made these changes & additions. Happy eyes :heart_eyes:

**Comment by marimuraki** [comment]
Next steps @alexsoble @AmirHadjihabib 

- move selector down closer to roster

**Comment by marimuraki** [comment]
@r11runner: Our designer @AmirHadjihabib noticed this issue, "The header is breaking to two lines and falling out of the grid". Do you know what might be going on?

![screen shot 2015-08-28 at 10 09 47 am](https://cloud.githubusercontent.com/assets/1334815/9552949/aa52b15c-4d70-11e5-9356-b7de8fd89f73.png)

**Comment by r11runner** [comment]
Thanks for the info. I'll have a look at it on Saturday.

**Comment by r11runner** [comment]
Sorry, my mistake. The reason is that the new header "STAR: Math" is actually wider than the content of the table cells. Hope that this css-change fixes the issue.

![header_star_math_nowrap](https://cloud.githubusercontent.com/assets/8597439/9561370/924f5894-4e42-11e5-9f32-28f66b9f1069.png)

**Comment by marimuraki** [comment]
Thank you, @r11runner! 

@AmirHadjihabib: Can you review these changes? In the screenshot, looks like there are some other weird things going on with the alignments and column headers. For example:

- "Home Language" is right-aligned
- "Level of Need" is funky-aligned
- "Percentile" under "STAR: Math" header is bleeding into the "ACCESS" header --- same for "504 Plan"

@AmirHadjihabib: Can you take a look at these issues this week?
