### ISSUE TITLE
Integrate data

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#25]
## Why

The goal of this feature is to support Somerville teachers. We talked with a team of teachers at Healey School in East Somerville. Here is some of what they told us about their current workflow:

+ “Everything I’m doing, it’s by hand. If it could be more efficient, it would save me time.”
+ “One of the biggest time wasters is, we’re looking at data from a test that we give. We ask, what did they do on MCAS last year? We pull up MCAS. What did they do on Star? We pull up Star.” 
+ “We take a lot of looks at the standards and how students are doing on those standards across different data sources. If we had a system in which we had a more effective way of doing standards analysis, it would save us a lot of time.” 
+ “Right now we do a lot of paper collaboration where we just print each other’s information.” 

By aggregating and linking data from different sources, our goal is to make life easier for the Healey teacher team: save time, facilitate collaboration, and reduce frustration.

![data](https://cloud.githubusercontent.com/assets/3209501/6542422/67a87848-c4ac-11e4-9a60-ab2a0f17c520.png)

## Milestones

Import data from different sources: 

+ [x] MCAS
+ [x] Star 
+ [ ] DIBELS
+ [ ] X2/Aspen
+ [ ] Interventions

**Comment by marimuraki** [comment]
@alexsoble Changed the issue title from "Aggregate data" to "Integrate data". "Aggregate" - in the data sense - implies more adding up instead of pulling together.

**Comment by alexsoble** [comment]
@marimuraki I like it!
