### ISSUE TITLE
Create summary overview in roster

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#252]
Teachers & principals both said that having a summary with basic overview of roster information would be helpful! @AmirHadjihabib started building it out today!

**Comment by marimuraki** [comment]
Check out https://github.com/codeforamerica/somerville-teacher-tool/issues/240

**Comment by marimuraki** [comment]
![screen shot 2015-08-21 at 3 28 54 pm](https://cloud.githubusercontent.com/assets/4615904/9420338/602cc8ee-4819-11e5-9acc-5d19a2a0c376.png)

**Comment by marimuraki** [comment]
New summary graph by @AmirHadjihabib 

![roster v3](https://cloud.githubusercontent.com/assets/4615904/9534672/1e5dd51a-4ccf-11e5-8fb3-0658bb7adf1b.png)

**Comment by marimuraki** [comment]
@AmirHadjihabib: Tomorrow let's [jsfiddle](http://jsfiddle.net/0juoLnfn/)!

**Comment by marimuraki** [comment]
@AmirHadjihabib: Re-opening this issue since we received feedback during our pilot that we should talk through. FYI: Jill liked the summary graph as the first step towards #169.

**Comment by alexsoble** [comment]
@marimuraki – Can you say more about the feedback we received? What do we need to change or fix?

**Comment by alexsoble** [comment]
Relates to homeroom roster redesign.
