### ISSUE TITLE
Multiple Select Grouping

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#265]
Now that we have subgroups in the Column selector it would be nice to add in high-level groupings.

http://harvesthq.github.io/chosen/#optgroup-support

![screen shot 2015-08-27 at 3 35 02 pm](https://cloud.githubusercontent.com/assets/4615904/9534941/84ae07ca-4cd1-11e5-81b7-8c50dbed40a7.png)

![screen shot 2015-08-27 at 3 38 34 pm](https://cloud.githubusercontent.com/assets/4615904/9534969/bde7bc66-4cd1-11e5-9d07-b27b29bbfd2a.png)

**Comment by r11runner** [comment]
Is it possible that the demographics columns aren't available at the moment (in the master branch)?

**Comment by marimuraki** [comment]
@r11runner: Not sure if this answers your question. Let me know.

The demographics and other data included in our tool would be categorized something like this (do not match the mock-up above) --->

- Name
- Risk Level
- Demographics
  - Program
  - Language
  - Free/Reduced Lunch
  - SPED & Disability
- MCAS
  - MCAS: Math
  - MCAS: ELA
- STAR
  - STAR: Math
  - STAR: ELA
- DIBELS
- ACCESS

**Comment by r11runner** [comment]
Thanks, yes, it answers my question. Sorry, I didn't formulate my question well. I was just wondering, because I hadn't seen the columns ELL, FLRP and LEP in the current version. The columns in your layout do ring a bell indeed.

**Comment by marimuraki** [comment]
Love it @alexsoble @AmirHadjihabib! 

Question: Are we going to keep the 6 max restriction? 

<img width="1058" alt="screenshot 2015-09-10 15 01 11" src="https://cloud.githubusercontent.com/assets/1334815/9802171/2128c544-57cd-11e5-8063-35d9b09fd8ae.png">
