### ISSUE TITLE
Select columns in roster table

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#269]
@alexsoble @AmirHadjihabib: "Select columns - max 5" is not consistent with what you can actually do. As shown below, you can select more than 5 variables and it will show up in the table.

<img width="1011" alt="screenshot 2015-08-30 23 44 16" src="https://cloud.githubusercontent.com/assets/1334815/9571773/3c8dba7e-4f71-11e5-8d39-347e38250c24.png">

We should either:
- set column max selection to 5 **OR**
- change "Select columns" wording

**Comment by alexsoble** [comment]
@marimuraki — Will add. :blush:
