### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#270]
There is no vertical scroll bar visible when the page extends beyond the browser boundary.

![screen shot 2015-08-31 at 1 27 23 pm](https://cloud.githubusercontent.com/assets/4615904/9589552/0afa7d9e-4fe4-11e5-86a3-bbaba8376f68.png)

**Comment by marimuraki** [comment]
Description from @r11runner:

"On the screen I see only some of the students, and if I want to see the students at the bottom of the list, I have to scroll down. But there is no scroll bar, I can only scroll down with the down arrow of the keyboard.

The issue appears with: Google Chrome 44.0.2403.155 (64-bit)
op. system: Ubuntu 14.04

With Firefox 40.0 I see a "normal" scroll bar."

**Comment by alexsoble** [comment]
Scrollbar is disabled in `table.scss`, lines 88-97. Was originally to prevent an ugly scrollbar on the roster table when too many columns were selected, but shouldn't be an issue now that we've implemented #269. We can remove those lines.
