### ISSUE TITLE
Add hover explanations

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#274]
During our Healey School start of school year pilot we heard from many educators spanning grades, subjects, etc. Not all educators understood the terminology asking:

- *"What does <= 2 level of need mean?"*
- *"What does 4.3 ACCESS level mean?"*

@alexsoble @AmirHadjihabib: Let's add a hover for the items that we received the most questions on *"what does this mean?"*

**Comment by marimuraki** [comment]
- Level of Need
  - http://www.doe.mass.edu/sped/iep/forms/pdf/PL3.pdf
- ACCESS
  - https://www.wida.us/assessment/access/#scores

**Comment by AmirHadjihabib** [comment]
Have this design from an earlier version. Working on creating the metaphor of dotted underlined items  being hoverable with explanations. 

![screen shot 2015-09-03 at 11 13 56 am](https://cloud.githubusercontent.com/assets/4615904/9666761/e670b90c-522c-11e5-91e9-e419fca28b3f.png)

https://www.dropbox.com/sh/88i1idb70xovhkk/AACJAf60rZ-b_7-MsgBat_MGa?dl=0

**Comment by marimuraki** [comment]
Yes @AmirHadjihabib exactly, we should add hovers with explanations for:

- ACCESS
- Disability: Level of Need
- Language Fluency (bunch of acronyms)

... and possibly a few more although the above two are the main ones we heard repeatedly.

I can draft the language of what the descriptions will sound like.

**Comment by marimuraki** [comment]
Another hover explanation:

*"Could a small text box with the cut-off scores be added to EACH assessment (MCAS, STAR, etc) . Teachers may not know what score constitutes a Needs Improvement vs a warning. Maybe the student just missed proficient by one point. Providing the ranges is helpful."* - Cheryl

**Comment by alexsoble** [comment]
Need to split this up, we will implement this for individual pages.
