### ISSUE TITLE
Add interaction between profile graph & timeline

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#275]
**Feedback from teacher during our Healey School pilot** when looking at the profile graph 

- *"Can I click on the graph so it'll take me to that profile section?"*

For example, the teacher was looking at the behavior graph. She saw the student had 10 behavior incidents in 2012. She clicked on that data point on the graph thinking it would take her to the profile timeline section with detailed behavior information. Instead she had to scroll down to find where this information was on the timeline.

@alexsoble @AmirHadjihabib: Thoughts? This may be a way to address the feedback from teachers on lots of scrolling.

**Comment by alexsoble** [comment]
Will be addressed as part of the #373 redesign: the designs show a much closer relationship between summary graphs and more detailed data.
