### ISSUE TITLE
Include teacher name & grade level to roster

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#276]
Idea from Marian to include teacher name for communication & collaboration purposes:

*"Could you have teacher names instead or in addition?? I was thinking that if a teacher (ie an ATP tutor or anyone other than the child's HR teacher) wanted to look up a child, they might only know the name of the child's HR teacher."*

When the tool is used during the MTSS meetings --- as Uri envisions it --- it would be helpful for the MTSS team to know which teacher to contact / connect with regarding a student rather than a homeroom number.

@AmirHadjihabib: What do you think? Where would you envision putting the teacher name on the roster?

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: At the MTSS & SST meetings, it became evident / was reiterated how the current way to find a student (SELECT homeroom >> wait for roster to load >> SORT name >> SCROLL down roster >> FIND student) is not efficient and actually quite difficult. Ideally, we need to build in a search so that students can be searched by name since teachers / staff know students by name, not by homeroom number.

As discussed with Jill & Uri and suggested by others:
- attach **teacher name** to **classroom number** in dropdown list
  - e.g., "HEA 100 - Muraki" instead of "HEA 100"
- add **grade** level view
  - https://github.com/codeforamerica/somerville-teacher-tool/issues/123
  - @ejegg: Missed your comment earlier on #123. Great feedback! Would love your ideas on this.
- build in search
  - during the SST meetings, students were discussed one after the other and, as currently designed, the tool would have been stalled the flow given how long it takes to find a student.

Currently:
<img width="236" alt="screenshot 2015-10-19 13 48 59" src="https://cloud.githubusercontent.com/assets/1334815/10586023/3d63648a-7668-11e5-9454-1491fcadfb04.png">

**Comment by alexsoble** [comment]
+ Searchbar: implemented and in production.
+ ATP tutor use case: out of scope.
