### ISSUE TITLE
Select / add multiple students to intervention

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#277]
Priority for Uri is the functionality of being able to assign multiple students to an interventions. This point was raised by teachers and principals as well so that assignments are not done repetitively one student at a time. 

Uri would like this functionality ready in time to test for the October MTSS meetings where teams will be identifying students in need of interventions.

@AmirHadjihabib: Uri brought up either 1) multi-select or 2) batch import from spreadsheet or 3) both. What do you think? Good question to ask the intervention support specialists as well about what might work best for them when they assign multiple students to an intervention.

**Comment by alexsoble** [comment]
Invision mockup via @AmirHadjihabib: https://projects.invisionapp.com/share/V845W3CYN

**Comment by marimuraki** [comment]
@AmirHadjihabib design: https://invis.io/V845W3CYN

Uri's feedback: *"Love that - really integrates it with the roster and also very intuitive way to add interventions in addition to just going in through the student history view."*

**Comment by AmirHadjihabib** [comment]
![roster - home 1 - menu](https://cloud.githubusercontent.com/assets/4615904/9822129/8b19814a-5873-11e5-9f42-f8d7050f3bfd.png)
