### ISSUE TITLE
Scope educator permissions to homerooms

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#278]
Educators should be able to see:

+ Their own homeroom
+ Other homerooms at the same grade level at their school
+ All homerooms, if they are a principal or district leader

Feedback from Healey teachers during our back-to-school pilot: 

+ _"can I get a login? how do I get access to this?"_  :+1:

**Comment by marimuraki** [comment]
@alexsoble: Another use case is for the ELL, special education, and resource teachers we met who said they support students **across** grade levels.

For now, maybe we can group these teachers similarly to the principal / admin level? Other ideas?

@jsgeiser: what do you think?

**Comment by alexsoble** [comment]
@marimuraki — I agree that we should group ELL, SPED, and resource teachers under the principal / admin level for right now. Let's build up the complexity of roles & permissions gradually rather than all at once.

**Comment by jsgeiser** [comment]
That kind of grouping sounds good. Each special education/resource room teacher actually services only two grade levels (1-2, 3-4, 5-6, 7-8). The ESL teachers have a wider span of grade levels. Also, some students see both special ed and ESL teachers (called "dually-identified students"). If they can pull students that they see as a whole group and by homeroom, that would be helpful I think.

**Comment by alexsoble** [comment]
+ Done for teachers, but we need a grade-level view for them to replace the dropdown. #123
+ Done for admins.
+ More work needs to be done to scope the roles Jill mentions like ESL teachers, interventionists, SPED teachers and other educators who are not assigned to one homeroom/grade level. #179
