### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#279]
So that educators see something in the Student Insights style when they run into an error.

**Comment by alexsoble** [comment]
Here's the default Heroku 404 page: 

![heroku 404](https://cloud.githubusercontent.com/assets/3209501/9701547/c82f7664-53fc-11e5-85a1-f791824c36eb.png)

**Comment by alexsoble** [comment]
One example when this might get served: if a non-admin teacher tries to log in and look at his/her homeroom, but s/he hasn't been assigned a homeroom yet in X2. The app won't know where to route the teacher and will serve up an error page like this.

**Comment by AmirHadjihabib** [comment]
Here is the design

![404](https://cloud.githubusercontent.com/assets/4615904/9822707/be2075e6-5876-11e5-8684-71dcfeae0e25.png)

**Comment by marimuraki** [comment]
@alexsoble: what is the status of this? do you need anything from @AmirHadjihabib to close up this issue?

**Comment by alexsoble** [comment]
@AmirHadjihabib: Could you send an SVG for the adorable planet when you have a chance?

Thanks!

**Comment by alexsoble** [comment]
Closed via #426.
