### ISSUE TITLE
Implement new Somerville risk level definitions

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#280]
New method of calculating risk levels for Somerville students starting this school year (2015-16).

**Comment by marimuraki** [comment]
We learned from Kenya that the **risk levels** were changed starting 2015-16 school year. Teachers have already received the PDF rosters with the new risk levels described below:

- no more Risk 0, now only Risk {1, 2, 3}
- changed formulas in order to *"identify kids who are really at risk"*
- include more criteria, not only assessment performance
  - MCAS performance level: ELA & Math
  - MCAS growth percentile: ELA & Math
  - English proficiency level
  - STAR grade equivalent: Reading & Math
  - STAR growth percentile
  - DIBELS level
  - grade level
  - % absent
  - age

@alexsoble @AmirHadjihabib: Will pull out the risk level rules from Kenya's new screenshots.

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Here are the new **risk level** rules. I've asked Kenya for the Healey School risk levels that she has already calculated so we can crosscheck for consistency / accuracy once we've re-coded these into our app.

These definitions are taken from Kenya's MS ACCESS formulas. We can provide refine some of these statements e.g., combine some redundancies.

1. Default all students are Risk Level 1
2. Replace students as Risk Level 2 if any of these criteria fit:
  - MCAS math performance level == "NI" **and** MCAS math growth percentile (GP) <= 35 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "NI" **and** MCAS ELA GP <= 35 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **OR**
  - MCAS math performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR Math Grade GE <= Grade in STAR-0.4 **OR**
  - English proficiency is "Limited" **and** 35 < ACCESS GP <= 60 **OR**
  - MCAS math performance level == "NI" **and** MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **OR**
  - DIBELS == "Strategic" **and** Grade is Kindergarten or 1st grade **OR**
  - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **and** grade 2
  - DIBELS == "Strategic" **and** Grade is 2nd grade **OR**
  - MCAS math performance level == "W" **and** % absent > 0.1 **and** Grade is NOT pre-K **OR**
  - MCAS ELA performance level == "W" **OR**
  - STAR Math GE <= Grade in STAR-0.4 **and** 2nd grade **OR**
  - age > Grade in STAR+6
3. Replace students as Risk Level 3 if any of these criteria fit:
  - [will show later]

**Comment by marimuraki** [comment]
cont'd ... @alexsoble @AmirHadjihabib: see a couple more possibly problematic issues with how Kenya defined the rules

3. Replace student as Risk Level 3 if any of these criteria fit:
  - MCAS math performance level == "W" **and** MCAS math growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR** :exclamation: :question: (why is SGP higher for Risk Level 3 than in Risk Level 2? follow-up with Kenya)
  - MCAS ELA performance level == "W" **and** MCAS ELA growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR** :exclamation: :question:
  - MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
  - MCAS math performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
  - English proficiency is "Limited" **and** ACCESS GP <= 35 **OR**
  - MCAS math performance level == "W" **and** MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **OR**
  - DIBELS == "Intensive" **and** Grade is Kindergarten or 1st grade **OR**
  - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** grade 2
  - STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** grade 2

  - age > Grade in STAR+7




  - DIBELS == "Strategic" **and** grade 2 **OR**
  - MCAS math performance level == "W" **and** % absent > 0.1 **and** Grade is NOT pre-K **OR**
  - MCAS ELA performance level == "W" **OR** :exclamation: :question: (follow-up with Kenya)
  - STAR math GE <= Grade in STAR-0.4 **and** 2nd grade **OR**

**Comment by marimuraki** [comment]
Follow-up response to Risk Level 2 :question: :exclamation: 

  - MCAS math performance level == "W" **and** % absent > 0.1 **and** Grade is NOT pre-K **OR**
  - MCAS ELA performance level == "W" **OR** :exclamation: :question: 

Follow-up response: *"The absence and grade level criterion were meant to be on a separate line as an Or condition."*

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Corrected & combined.

1. Default all students are Risk Level 1
2. Replace students as Risk Level 2 if any of these criteria fit:
  - MCAS math performance level == "NI" **and** MCAS math growth percentile (GP) <= 35 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "NI" **and** MCAS ELA GP <= 35 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **OR**
  - MCAS math performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR math Grade GE <= Grade in STAR-0.4 **OR**
  - English proficiency is "Limited" **and** 35 < ACCESS GP <= 60 **OR**
  - MCAS math performance level == "NI" **and** MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **OR**
  - DIBELS == "Strategic" **and** Grade is Kindergarten or 1st grade **OR**
  - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **and** grade 2
  - DIBELS == "Strategic" **and** Grade is 2nd grade **OR**
  - MCAS math performance level == "W" **OR**
  - MCAS ELA performance level == "W" **OR**
  - % absent > 0.1 **and** Grade is NOT pre-K
  - STAR math GE <= Grade in STAR-0.4 **and** grade 2 **OR**
  - age > Grade in STAR+6
3. Replace student as Risk Level 3 if any of these criteria fit:
  - MCAS math performance level == "W" **and** MCAS math growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "W" **and** MCAS ELA growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR**
  - MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
  - MCAS math performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
  - English proficiency is "Limited" **and** ACCESS GP <= 35 **OR**
  - MCAS math performance level == "W" **and** MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **OR**
  - DIBELS == "Intensive" **and** Grade is Kindergarten or 1st grade **OR**
  - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** grade 2 **OR**
  - STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** grade 2 **OR**
  - % absent > 0.2 **OR**
  - age > Grade in STAR+7

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Categorizing based on assessment and other groupings.

**Risk Level 2** 
  - MCAS
    - MCAS math performance level == "W" **OR**
    - MCAS ELA performance level == "W" **OR**
  - STAR
    - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **and** Grade 2 **OR**
    - STAR math GE <= Grade in STAR-0.4 **and** Grade 2 **OR**
  - MCAS & English proficiency
    - MCAS math performance level == "NI" **and** MCAS math growth percentile (GP) <= 35 **and** English proficiency is NOT "Limited" **OR**
    - MCAS ELA performance level == "NI" **and** MCAS ELA GP <= 35 **and** English proficiency is NOT "Limited" **OR**
    - MCAS math performance level == "NI" **and** MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **OR**
  - MCAS & STAR & English proficiency 
    - MCAS ELA performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.4 **OR**
    - MCAS math performance level == "NI" **and** English proficiency is NOT "Limited" **and** STAR math Grade GE <= Grade in STAR-0.4 **OR**
  - ACCESS & English proficiency
    - English proficiency is "Limited" **and** 35 < ACCESS GP <= 60 **OR**
  - DIBELS
    - DIBELS == "Strategic" **and** Grade is Kindergarten or 1st grade **OR**
    - DIBELS == "Strategic" **and** Grade 2 **OR**
  - Absence
    - % absent > 0.1 **and** Grade is NOT pre-K **OR**
  - Age
    - age > Grade in STAR+6

**Risk Level 3** 
  - STAR
  - MCAS & English proficiency
    - MCAS math performance level == "W" **and** MCAS math growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR**
    - MCAS ELA performance level == "W" **and** MCAS ELA growth percentile (GP) <= 40 **and** English proficiency is NOT "Limited" **OR**
    - MCAS math performance level == "W" **and** MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **OR**
  - MCAS & STAR & English proficiency 
    - MCAS ELA performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
    - MCAS math performance level == "W" **and** English proficiency is NOT "Limited" **and** STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **OR**
  - ACCESS & English proficiency
    - English proficiency is "Limited" **and** ACCESS GP <= 35 **OR**
  - DIBELS
    - DIBELS == "Intensive" **and** Grade is Kindergarten or 1st grade **OR**
  - DIBELS & STAR
    - STAR Reading Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** grade 2 **OR**
    - STAR math Grade Equivalent (GE) <= Grade in STAR-0.8 **and** DIBELS == "Intensive" **and** Grade 2 **OR**
  - Absence
    - % absent > 0.2 **OR**
  - Age
    - age > Grade in STAR+7

**Comment by r11runner** [comment]
"Default all students are Risk Level 1"
Does it mean that the risk level N/A isn't used any more?

**Comment by r11runner** [comment]
@alexsoble
Can you please have a look at https://github.com/r11runner/somerville-teacher-tool/tree/risk-levels ?
In this branch I experimented with an approach where all risk level criteria is implemented in its own class. These are located in the folder app/models/risk_level_specifications and inherit from a base class RiskLevelSpecification
The class StudentRiskLevel calculates the risk level, as it iterates through these RiskLevelSpecification-subclasses

At the moment it is only in draft state:
 - only 2 subclasses of RiskLevelSpecification
 - explanations: no handling for special cases
 - the method update_risk_level! should be refactored
 - no new tests
 - I haven't changed the old tests => they're red
etc. 
But this draft is perhaps enough to start a discussion :-)

I can do some refinements and implement further risk level criteria, if you think that it makes sense to go further into this direction.

**Comment by marimuraki** [comment]
@r11runner: Great question (RE: Does it mean that the risk level N/A isn't used any more?)

The risk level will be N/A if all values are missing.

Thanks for taking a stab at the new student risk level definitions! We'll take a look.

**Comment by marimuraki** [comment]
@r11runner: We took a look at your branch and definitely looks like the direction to go with the subclasses for:

- MCAS
- STAR
- DIBELS
- ACCESS
- Other
  - absence (we currently don't have this anywhere and might be a non-trivial calculation)
  - age

**Comment by r11runner** [comment]
Thanks for the quick feedback.
I'll implement some subclasses on Wednesday and inform you about the progress.

**Comment by r11runner** [comment]
Sorry, I couldn't spend too much time with it in the last 2 days. I'll let you know, if there are other subclasses.

**Comment by r11runner** [comment]
The branch https://github.com/r11runner/somerville-teacher-tool/tree/risk-levels now contains the risk level calculations for:
 - MCAS
 - MCAS & English proficiency
 - ACCESS & English proficiency
 - part of DIBELS
There is still a lot to refactor, but the calculations should be correct.

A question:
Several risk level specs contain STAR Grade Equivalent.
Where is it stored? I saw only percentile rank and instructional reading level on the roster and in the db in the table student_assessments as well.

**Comment by marimuraki** [comment]
@r11runner: Great, thank you!

Yes, there are some variables that @alexsoble & I still need to pull in or calculate including:

- age
- % absence (this might be a bit complicated, we are looking into it)
- grade equivalent (I will look into this)

I'll get back to you with more specifics on those.

**Comment by marimuraki** [comment]
So we just received a [SIF](http://www.doe.mass.edu/infoservices/data/sif/) file for the latest year that includes:

- `days_in_attendance`
- `days_in_membership`

from which we can calculate % absence.

I've emailed John if he can provide us with all years of SIF files. Based on what he says, it is complicated to calculated % absence from the X2 tables but if we can, I think it would be better than pulling in new data files. Would prefer to stick to using X2 as the main source (especially if John creates SIF based off of X2 anyway). I'll let you now what I hear back.

**Comment by alexsoble** [comment]
We are meeting with Kenya this week — we will talk about what next year's definitions might look like. We are going to advocate for simpler definitions that are easier to understand and (as a side benefit) easier to code.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/22.
