### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#283]
Work to improve the tables in Student Insights.

![roster - home 1](https://cloud.githubusercontent.com/assets/4615904/9822141/99c398de-5873-11e5-98e1-10e4a7385db9.png)
![roster - home 2](https://cloud.githubusercontent.com/assets/4615904/9822139/99bf562a-5873-11e5-9ff4-c6151dddbac4.png)
![roster - home 3](https://cloud.githubusercontent.com/assets/4615904/9822140/99c007c8-5873-11e5-962e-fc1120e65738.png)

**Comment by marimuraki** [comment]
@AmirHadjihabib: Nice! What are the actions that can be done when clicking on the check boxes? Does that only show up when adding interventions or are there other use cases?

**Comment by AmirHadjihabib** [comment]
For now it would be for bulk adding interventions in the future it could have more flows. 

Prototype of bulk actions and table scrolling
https://invis.io/V845W3CYN

**Comment by alexsoble** [comment]
Closed with #292.
