### ISSUE TITLE
Fix front-end funkiness in Firefox

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#290]
FFFF! or Fix front-end funkiness in Firefox!

@alexsoble @AmirHadjihabib: In Firefox, intervention header does not stick to the column.

**Firefox** looks funky!
![screenshot 2015-09-21 14 02 52](https://cloud.githubusercontent.com/assets/1334815/10005079/1d389f86-606a-11e5-97b5-47e4f1bb461c.png)

**Chrome** looks cute!
![screenshot 2015-09-21 14 08 52](https://cloud.githubusercontent.com/assets/1334815/10005115/516a7216-606a-11e5-8bb3-5234425d0973.png)

**Comment by alexsoble** [comment]
A little bit better!

__Firefox screenshot__:

![fix-firefox-screenshot](https://cloud.githubusercontent.com/assets/3209501/10037484/9859fdfc-616b-11e5-950f-92e1d7cb0834.png)
