### ISSUE TITLE
Fix columns headers in roster

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#295]
When adding and then removing a column with a double header, the intervention +N pill gets cut off.

![screen shot 2015-09-25 at 1 48 27 pm](https://cloud.githubusercontent.com/assets/1334815/10112172/dd2abdd0-638d-11e5-85cf-95cd5e28140b.png)

![screen shot 2015-09-25 at 1 46 53 pm](https://cloud.githubusercontent.com/assets/1334815/10112173/e0c3feac-638d-11e5-9c7b-fbf8b3a9bae1.png)

**Comment by alexsoble** [comment]
@marimuraki: Can you still replicate this issue?

**Comment by marimuraki** [comment]
Yes, @alexsoble: this is still an issue.

A related observation that might help troubleshoot is ... as I was replicating the issue is that the "..." disappears if a double header column is not included.

<img width="1049" alt="screenshot 2015-10-21 13 09 59" src="https://cloud.githubusercontent.com/assets/1334815/10648804/8290a4bc-77f5-11e5-8c91-f9e5d0bb4c44.png">


Here is a gif:

![licecap_smvtt_roster_bug](https://cloud.githubusercontent.com/assets/1334815/10648795/771da346-77f5-11e5-9dac-6c21e50c1a5c.gif)


cc' @AmirHadjihabib

**Comment by alexsoble** [comment]
Small bug
