### ISSUE TITLE
Expand roster selection drop-down's clickable area

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#298]
Currently the user has to click in the box. Even with my amazing dexterity =) I find it difficult to click in the box accurately. 

@AmirHadjihabib: Can we expand the click area to include the variable names?

<img width="176" alt="screenshot 2015-10-05 13 43 32" src="https://cloud.githubusercontent.com/assets/1334815/10293016/23db1172-6b67-11e5-9ec1-31c17d52670b.png">

**Comment by alexsoble** [comment]
We haven't gotten feedback from anyone else that this is a problem. Also this feature is likely going to be redesigned in the medium-future so we won't focus on UI here.
