### ISSUE TITLE
Refine DIBELS information in profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#299]
From Cheryl (reading tutor at Healey):

*"This is helpful to have the overall - core, strategic, at risk but could the individual subtests be added? For grade 1 - the DIBELS includes Letter Naming, Phoneme Segmentation, and Nonsense Word Fluency measures. Including those sub-test scores that made-up the overall."*

**Comment by marimuraki** [comment]
Also Uri mentioned how all administrations (not just latest in a given year) is important.

*"In terms of historical DIBELS, the latest one should show up in the roster, and then all the past ones would show up in the student profile."*

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Heard again how DIBELS information needs to be refined.

**Show by subject, not only composite**

Spoke with Colette about DIBELS. She uses DIBELS as a primary source of information on fluency. She said that it's crucial to her interventions to have not only the levels (CORE, STRATEGIC, INTENSIVE) but also the scores which she uses to differentiate within the levels. She also said that Somerville (Uri) adjusts the thresholds for which scores are in which level and so would be helpful to see those underlying scores.

- Letter Naming Fluency (LNF)
- Initial Sound Fluency (ISF)
- Phoneme Segmentation Fluency (PSF)
- Nonsense Word Fluency (NWF)
- Oral Reading Fluency (ORF)
- Word Use Fluency (WUF)

https://dibels.uoregon.edu/docs/materials/admin_and_scoring_6th_ed.pdf

We have this data in X2.

**Show all DIBELS administrations**

She also said that showing all three administrations of DIBELS for each year is important. She looks at these scores to assess progress within the year.

Currently she has this information on the student's DIBELS booklet.

**Comment by marimuraki** [comment]
For **DIBELS** in `assessment_export` file, we have:

- 3 administrations (`assessment_subject`) by following months (`assessment_date`)
  - Administration # 1 in September / Oct
  - Administration # 2 in January
  - Administration # 3 in May

`tab assessment_date2 assessment_subject if assessment_test == "DIBELS"`

| Administration | 1 | 2 | 3 |
| ----- |:-----:|:-----:|:-----:|
| Jan | 0 | 5506 | 0 |
| May | 0 | 0 | 5261 |
| Sep | 827 | 0 | 0 |
| Oct | 6902 | 0 | 0 |



cc' @alexsoble

**Comment by marimuraki** [comment]
@alexsoble: Looking at the underlying DIBELS data, this is a non-trivial parsing task since the growth scores by domain are manually inputted into a single cell without a standard format. Fortunately there are patterns that we can take advantage of.

O: #
ORF: #
ISF: #,LNF: #
I: #,L: #,P:,NC:,NW:
ISF: #,LNF: #,PSF: #,NW
LNF: #,PSF: #,NWF: #
etc ... 

We would need to parse the text to:

- parse each domain
  - separated by `,` 
- grab the domain e.g., LNF, PSF, ... preceding `:` 
- grab the score
  - follows `:` e.g., "LNF: "
  - score may be missing
- order the [domain:score] pairs to display by domain category

NOTE:  as of 20151026 download

Observed the following domains in `assessment_growth`:

- I
- ISF
- L
- LNF
- NC
- NW
- NWF
- O
- ORF
- P
- PSF

Assumption is that many of these categories are the same e.g., I = ISF, L = LNF, etc

**Comment by marimuraki** [comment]
@alexsoble: Flagging this as higher up on priority for next year (post-Fellowship). During the SST & MTSS meetings we observed how teachers often referenced the specific DIBELS domains e.g., "Johnny has a X in non-sense word fluency ... it went down from Y", "Mary's oral fluency score on DIBELS is X, up from Y", etc. 

DIBELS also seems like a key measure referenced and monitored by teachers, reading specialists, and principals. For example, Jill specifically asked a specialist to test non-sense work fluency after a period of intervention to measure progress.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/23.
