### ISSUE TITLE
Combine data

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#30]
##### Description:
...

##### User stories:
As a teacher, I want to see my classroom’s data from different sources in one location so that I can have a better holistic view of my students.

##### Ready stories:
* [ ] #29 
* [ ] #28

**Comment by alexsoble** [comment]
Looks like this duplicates #25...

**Comment by marimuraki** [comment]
@AmirHadjihabib Can you move this issue into @alexsoble's #25?
