### ISSUE TITLE
Interventions dropdown not populated

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#302]
@alexsoble: The interventions dropdown is blank on the production site. Uri & Jill want to add interventions this week. Can you look into what is going on as soon as possible?

**Production**
<img width="358" alt="screenshot 2015-10-14 09 08 11" src="https://cloud.githubusercontent.com/assets/1334815/10484909/d2c546c2-7255-11e5-97d2-18b9242fd947.png">

**Demo**
<img width="395" alt="screenshot 2015-10-14 09 20 36" src="https://cloud.githubusercontent.com/assets/1334815/10484916/d9fd946c-7255-11e5-9dd4-2ee1753fc87b.png">

**Comment by alexsoble** [comment]
Fixed. :+1:
