### ISSUE TITLE
Include additional fields to intervention modules

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#303]
Lots of observations from Healey School's MTSS meeting. A standardized intake form exists where the team (in today's case, the Assistant Principal Bridget Dowling) had / updated / collected the following key information. 

- student name / ID
- referring teacher
- date received
- SPED status
- concerns at-a-glance
- MTSS initial date
- pre-referral meeting date
- results
- status determination / rationale
- referred to special education (Y/N)
- renewal staff
- notes

@alexsoble @AmirHadjihabib: I will discuss more with Jill & Uri on which of these key indicators / information might be important to include in the interventions module.

**Comment by marimuraki** [comment]
From **MTSS referral form**:

- referring teacher
- referral classification
  - academic
  - behavioral
- initial referral date
- meeting date(s)
- child study team
- assessments
  - MCAS
  - DIBELS
  - Fountas & Pinnell
  - MAP
- attendance
  - days absence
  - days tardy
- areas of concern
- interventions
  - tier I
  - tier II
    - identified need
    - 30 day goal
    - intervention strategies
    - frequency
    - assessment strategy
    - staff
    - response to intervention
    - progress notes

**Guiding questions**
  - During what time of day or classes do the problems occur?
  - What related skill deficits can be identified?
  - Why does the student struggle to use or learn these skills?
  - What problems does the student have accessing curriculum or instruction?
  - What patterns and relationships can be identified?
  - What data or information is missing to help identify the core issues?
  - What logistical problems can be anticipated?

**Action items**
  - task & assigned staff

**Parent Consult**
  - consultation date
  - notes e.g., information, questions, concerns

**SPED Referral**
  - Y/N
  - notes e.g., rationale

**Comment by marimuraki** [comment]
After SST meeting & Jill / Uri meeting:

- [ ] add in checkboxes for whether referred to & discussed at MTSS or SST meeting
- [ ] add column to identify from roster who was referred to MTSS or SST
- [ ] add tag to assign staff to intervention next steps
  - including email notification / reminder

@jsgeiser: Any feedback on this interaction, wording, etc?

> Discussed at: 
> - [ ] MTSS 
> - [ ] SST 

before "Select Intervention" inside intervention module

> Assigned to [ name ] 

after "End date" inside intervention module

Currently looks like:

<img width="353" alt="screenshot 2015-10-19 15 16 03" src="https://cloud.githubusercontent.com/assets/1334815/10588643/337f2064-7675-11e5-9d4b-c7f4c3ee3887.png">

@alexsoble @AmirHadjihabib: thoughts?

**Comment by jsgeiser** [comment]
I would put the "assigned to" before the "End date". Also a student can be assigned an intervention through the MTSS and SST processes, which is what the "discussed at" encompasses (e.g. "intervention was discussed at MTSS / SST"). I also wonder if we should have an intervention labeled "Referred to MTSS", "Referred to SST". This would help staff know that the referral has been made even if no interventions through those processes have been identified yet. The referral itself is a kind of intervention. Not sure if this would be too redundant (?).

**Comment by marimuraki** [comment]
Thank you @jsgeiser! Yes, I have included the MTSS & SST referrals in the updated interventions list here: https://github.com/codeforamerica/somerville-teacher-tool/issues/306

Does this list https://github.com/codeforamerica/somerville-teacher-tool/issues/306  look good?
