### ISSUE TITLE
Update interventions list

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#306]
Jill & Uri have corrections (~~strike~~) & additions (**bolded**) to the interventions list. 

@jsgeiser: Please correct or add / remove any interventions.

- After-School Tutoring (ATP)
- Attendance Officer
- Attendance Contract
- Behavior Contract
- Behavior Plan
- Before School Tutoring
- Boys & Girls Club
- Community Schools
- ~~In-House~~ **Counseling: In-House**
- ~~Outside~~ **Counseling: Outside/Physician Referral**
- **ER Referral (Mental Health)**
- Math ~~Teacher~~ **Tutor**
- **Mobile Crisis Referral**
- **MTSS Referral**
- **OT / PT Consult**
- **Parent Conference/Meeting**
- ~~Phone Call~~ **Parent Communication**
- Peer Mediation
- Reading ~~Teacher~~ **Tutor**
- **SST Referral**
- Teaching Plan
- Weekly Call/Email Home
- X Block Tutor
- 51a Filing
- Other

**Current intervention list:**

<img width="355" alt="screenshot 2015-10-19 11 37 37" src="https://cloud.githubusercontent.com/assets/1334815/10582457/f4f9568a-7655-11e5-8aaa-2a5215e2fc71.png">

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: Jill discussed how while not specifically an intervention, it would be nice to be able to keep a log / records of things like:

- behaviors (not captured in discipline records but collected by teachers in their own classroom logs)
- parent contact (communications not specifically tied to an intervention)

She said that the current flow of the interventions would work for recording these additional types of actions: a log history. Suggested "Interventions" >> "Interventions / Information Log, ?, ? ...". Distinction being: interventions = do & apply vs. log = record. Open to ideas.

**Comment by jsgeiser** [comment]
Not sure what "teaching plan" is. This could be a classroom intervention that the classroom teacher does assigned through MTSS process. That could be labeled instead "classroom academic intervention" and another "classroom behavior intervention".

**Comment by jsgeiser** [comment]
You could get rid of "before school tutoring" since it would be covered under "reading tutoring" and "math tutoring".

**Comment by jsgeiser** [comment]
Maybe add "reading services". This would be different from "reading tutor" in that it would be done by the reading specialist.

**Comment by marimuraki** [comment]
@jsgeiser: Made the changes. Look good?

- After-School Tutoring (ATP)
- Attendance Officer
- Attendance Contract
- Behavior Contract
- Behavior Plan
- Boys & Girls Club
- Classroom Academic
- Classroom Behavior
- Community Schools
- Counseling: In-House
- Counseling: Outside/Physician Referral
- ER Referral (Mental Health)
- Math Tutor
- Mobile Crisis Referral
- MTSS Referral
- OT/PT Consult
- Parent Conference/Meeting
- Parent Communication
- Peer Mediation
- Reading Specialist
- Reading Tutor
- SST Referral
- Weekly Call/Email Home
- X Block Tutor
- 51a Filing
- Other

**Comment by jsgeiser** [comment]
Mari's distinction between doing and recording is a good one. The recording would help to share information between staff members and keep it in one place even it is not an action item. That would help save time 'information chasing' and duplicating work by more that one person. Maybe it could go with the intervention (?) but not sure if that would be too confusing and should be separated out.

**Comment by jsgeiser** [comment]
List looks good. I would add the word "intervention" to classroom academic and behavior. It is a bit repetitive but "intervention" gives it more context and people will know what it means than if it is left out.

**Comment by alexsoble** [comment]
Updated in production.
