### ISSUE TITLE
Assign educator to interventions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#307]
As observed at MTSS meeting, specific staff are assigned to next steps e.g., make phone call, schedule meeting, complete assessment, etc. In order to keep track of who is responsible and be able to follow-up accordingly, ideas discussed included:

- add tag to assign staff
- add email notification / alert to assigned staff

@alexsoble @AmirHadjihabib: Refer also to #303

**Comment by marimuraki** [comment]
In meeting with Jill & Bridget today, feature that is key in SST meetings is the ability to assign educators to interventions. 

Currently Jill has been including the assigned educator in the comment section but being able to assign an educator will let them:

- log & track (who is responsible for an intervention)
- notify / remind
- followup

**Comment by alexsoble** [comment]
Complete in the current iteration. We will be redesigning the intervention process based on what we've observed and discussed with Jill Geiser this month.
