### ISSUE TITLE
Student searchbar?

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#309]
@marimuraki @jsgeiser

Talking with Mari, I heard about one issue that came up during the student support team meeting: the time it takes to reach an individual student's profile and add an intervention. 

Mari mentioned the idea of a search bar for locating a particular student by name. How does this GIF seem to you two as a potential solution?

![student-searchbar](https://cloud.githubusercontent.com/assets/3209501/10606541/39126eda-76f9-11e5-8942-8b484eef6e15.gif)

**Comment by marimuraki** [comment]
Looks good, @alexsoble! Thanks for creating a separate issue on search --- I had snuck it into #276 :smile: 

**Question**: How could we differentiate between students who have the same name? 

I'm not sure how common this is in Somerville (I can check) but having worked at school districts like San Francisco Unified and Miami-Dade, it is not uncommon to have students in the same school / grade / classroom with the same common name e.g., "Selena Gomez", "Alejandro Sanz", etc

**Comment by alexsoble** [comment]
@marimuraki — Could be limited by school. Likelihood of students in the same school with same name smaller than students in same district with same name.

**Comment by marimuraki** [comment]
@alexsoble: Smaller likelihood is a scenario. I think we should consider this case (also especially if we want to be extensible to other school districts). It's not as uncommon as you might this based on the schools' data I have worked with. True, in terms of magnitude smaller in smaller schools but to me small likelihood == high likelihood != 0 likelihood.

**Comment by marimuraki** [comment]
@alexsoble: So in Somerville, looks like there are only 2 students with the same name in the same school (... might also be a data entry issue).

- same name
- same school
- different IDs (local & state)
- different grade level
- different homeroom

**Comment by alexsoble** [comment]
@marimuraki — Gotcha, so we could use grade level as a good differentiator.

**Comment by marimuraki** [comment]
@alexsoble: Question on the design cc @AmirHadjihabib

Right now the search bar is placed next to the "Homeroom" dropdown list so looks like the student search is only **within that specified homeroom**. 

Is this the flow you built here https://github.com/codeforamerica/somerville-teacher-tool/pull/311? 

I assume that we want to be able to search globally within that school. If that's the flow already, think we should move the search bar above the "Homeroom" dropdown to avoid confusion.

**Comment by alexsoble** [comment]
@marimuraki Globally.

**Comment by alexsoble** [comment]
@marimuraki I think the point about the search bar positioning is a good one. Positioning the search bar above still makes it look like homeroom-specific search to me:

![above](https://cloud.githubusercontent.com/assets/3209501/10612288/c00a380c-7715-11e5-8b1a-5fb8bb8df464.png)

**Comment by alexsoble** [comment]
@marimuraki What do you think about student search bar to the left of homeroom dropdown?

![next to](https://cloud.githubusercontent.com/assets/3209501/10612340/f85b48d6-7715-11e5-8032-e28059521047.png)

**Comment by marimuraki** [comment]
@alexsoble: So from what I understand, the current search flow will take you to the student's PROFILE **regardless** of the current homeroom view / selected homeroom in dropdown list. Given that the search has no relationship to the homeroom or roster view, it makes more sense to me to have separate those.

Now if the flow of the search is modified to:
- show the roster with the students that match that name
- list only those homerooms in the dropdown that are relevant
  - user can then drill down into a homeroom to see only those student matches within that homeroom
  - in Somerville, likely only one homeroom

... then the 3rd design make sense.

cc' @AmirHadjihabib

**Comment by alexsoble** [comment]
@marimuraki 

I see... How about this then?

![above above](https://cloud.githubusercontent.com/assets/3209501/10613626/944420b0-771b-11e5-9d31-b3fadf97168a.png)

**Comment by marimuraki** [comment]
@alexsoble: Of the designs, I like this option if the flow is Search >> Profile. Otherwise, for the flow Search >> Roster, I like the 3rd.

Separate but related question (didn't notice it before): What is the purpose of that "Roster" link?

**Comment by alexsoble** [comment]
@marimuraki: What do you this is the best flow option? If the goal is to let educators get to the profile view the quickest to add interventions / comments for individual students, I would say Search >> Profile is best.

**Comment by alexsoble** [comment]
@marimuraki: And you're right, the 'Roster' link doesn't make much sense on the Roster page. :)

**Comment by marimuraki** [comment]
@alexsoble: The Search >> Profile makes sense:

1. find student
2. review student profile information
3. add intervention / progress notes

@jsgeiser: Does this search / work flow work well in the context of the SST / MTSS meetings?

So then the last design makes sense (minus the "Roster" link). 

Also, what do you think of the text "Search for student" instead of just "Student"?

cc' @AmirHadjihabib

**Comment by alexsoble** [comment]
@marimuraki "Search for student" makes sense!

**Comment by jsgeiser** [comment]
That makes sense for work flow. IN the HR dropdown menu, what about an "All Students" option (with it defaulting there then you can pick a HR if you want to search within just one HR)? I also wonder if once you write in the student's name (using first or last), a list of students with that name comes up in a roster first and you click on the students name to get to their page. That is an interface similar to what we usually have in app's/databases that we currently use. Sometimes when looking for a student, we might have only a part of the name and want to be sure we have everyone listed in the school to know we have the right student.

**Comment by jsgeiser** [comment]
Also, if it appears in a roster, grade level or even HR could be a differentiator.

**Comment by marimuraki** [comment]
Thanks @jsgeiser! @alexsoble, thoughts? Re-opening this issue as we continue the convo around refining search.

**Comment by alexsoble** [comment]
@jsgeiser @marimuraki — We should draw out these ideas when we're all back in Somerville, don't have a clear visualization in mind of what this feature would look like right now.

**Comment by marimuraki** [comment]
@alexsoble: Sounds good! I have a good idea of what @jsgeiser is describing so let's us touch base on Monday when you are back in the office to sketch it out.

**Comment by jsgeiser** [comment]
I can be available by phone if you want to talk more about it.

**Comment by alexsoble** [comment]
Closing this main issue since the search bar is built.

Opening two new ones to reflect planned enhancement based on Jill's feedback, plus a bugfix:

+ #410
+ #411
