### ISSUE TITLE
Add homeroom to student profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#314]
Let's add homeroom & teacher to student profile. Now that we have the student search function, a student profile can be accessed without first going through the homeroom roster.

For example, a user can be:
- viewing homeroom 100 roster
- search for "Daisy Duck" with homeroom 100 roster in current view
- sent to profile for "Daisy Duck" **but** "Daisy Duck" is NOT in homeroom 100
- currently no way to know what homeroom / teacher "Daisy Duck" is in
   - "I want to see the homeroom roster for "Daisy Duck" but don't know which it is"

**What might help?** @alexsoble @AmirHadjihabib 
- show homeroom / teacher in profile 

We could include it under "Information":
<img width="434" alt="screenshot 2015-10-21 11 47 49" src="https://cloud.githubusercontent.com/assets/1334815/10646719/9a3bc8f0-77e9-11e5-8816-f9ecc4748b03.png">

**Comment by alexsoble** [comment]
This exists now and will get even more prominent after #373 is implemented.
