### ISSUE TITLE
Maintain formatting in text box

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#319]
@alexsoble: Making a separate issue for the formatting text box issue since this will be something tackled more extensively later. Refer to discussion with @jsgeiser in #312.

**Before Save**
<img width="548" alt="screenshot 2015-10-22 12 43 39" src="https://cloud.githubusercontent.com/assets/1334815/10676558/05767aca-78bc-11e5-9ede-48c6b61d4448.png">

**After Save**
<img width="994" alt="screenshot 2015-10-22 12 49 25" src="https://cloud.githubusercontent.com/assets/1334815/10676485/5dd6a2e0-78bb-11e5-8862-7d2b7c9ca21f.png">

**Comment by alexsoble** [comment]
Important issue, part of #373.

**Comment by kevinrobinson** [comment]
@alexsoble I think this is closed by https://github.com/codeforamerica/somerville-teacher-tool/pull/422 now, and we've got the link to make sure it's captured as part of the work for #373 too.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/5.
