### ISSUE TITLE
Add timestamp to date in progress notes?

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#323]
@alexsoble: What do you think about adding a timestamp to the progress notes?

Here is an example. Might be useful to be able to differentiate calls on the same day but at different times. Right now it simply shows date and the user will need to know that the first record (below: "hello again!") is the most recent record --- or include the time in their notes. @jsgeiser: thoughts?

<img width="553" alt="screenshot 2015-10-27 11 27 07" src="https://cloud.githubusercontent.com/assets/1334815/10768439/50e68c6c-7c9e-11e5-9415-02d8428f2a9d.png">

cc' @AmirHadjihabib

**Comment by alexsoble** [comment]
@marimuraki — Good feature idea. We'll have to set up a strategy for dealing with time zones to make this work.

**Comment by marimuraki** [comment]
@alexsoble: What timezone is the date currently set to? e.g., 11 pm PT 2015-10-**27** is 2 am ET 2015-10-**28**.

**Comment by marimuraki** [comment]
I like, @alexsoble! :+1: The "Progress Notes" header and the timestamp make it a lot more readable already.

<img width="558" alt="screenshot 2015-10-27 12 09 58" src="https://cloud.githubusercontent.com/assets/1334815/10769510/ba06dc6a-7ca3-11e5-91f5-aaff5955e433.png">

Thoughts on **email** emphasis?

**Comment by jsgeiser** [comment]
I like the timestamp. It will actually help to know what interventions are being inputted during meetings.

**Comment by marimuraki** [comment]
@jsgeiser: Great! :+1: The updates to the interventions module are now live so feel free to log in and test it out. We would love your feedback on anything we can improve before next week. 

Feel free to open new issues on GitHub if needed. Thank you! :blush:

**Comment by alexsoble** [comment]
Student profile / intervention tracking redesign in progress: #373
