### ISSUE TITLE
Tweak progress notes design

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#324]
In the progress notes, I feel like the **emails** (**bolded**) e.g., **demo[at]example.com**, **fake-fifth-grade[at]example.com** stand out more that the actual progress notes.

What do you think about putting the email next to the date? Or, another way to make the progress note be displayed as the more important piece of information. @AmirHadjihabib: ideas?

In the scenario of multi-team collaboration, a prominent email might be useful to see who did what but in the case of a teacher logging her / his own progress notes, having a long text history with their email repeatedly bolded seems distracting to the real content:

**fake-fifth-grade[at]example.com**
important progress note update
**fake-fifth-grade[at]example.com**
important progress note update
**fake-fifth-grade[at]example.com**
important progress note update
**fake-fifth-grade[at]example.com**
important progress note update
**fake-fifth-grade[at]example.com**
important progress note update
**fake-fifth-grade[at]example.com**
important progress note update

<img width="553" alt="screenshot 2015-10-27 11 27 07" src="https://cloud.githubusercontent.com/assets/1334815/10768494/accb5ca6-7c9e-11e5-8330-fd7c0dd3ff6b.png">

**Comment by alexsoble** [comment]
Student profile / intervention tracking redesign in progress: #373
