### ISSUE TITLE
Improve session timeout experience

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#326]
@jsgeiser flagged a problem today:

*"Just want to let you know that we started to input some intervention information into Student Insights ... however when I click save, it's not saving."*

I investigated the issue and think I was able to replicate it:

- intervention module was open in browser
- session timed out (15+ min)
- **BUT** visually NO indication that she was logged out ... so when she tried to add an intervention, the tool was not active
- after signing back, interventions module works

**Solution?** @alexsoble 

- log out user and take to sign in page

**Comment by marimuraki** [comment]
Feedback from Jill:

*"Yes that makes sense! I clicked on “back to roster” and it brought me to the log in page. It is possible that we might sit on an intervention page for several minutes before clicking save. Maybe set it up so that the typing activity keeps it logged in if that’s possible?"*

**Comment by marimuraki** [comment]
Example of time out: https://www.ssa.gov/accessibility/bpl/bps/forms/timeout/example/default.htm

**Comment by alexsoble** [comment]
Closed via #330.
