### ISSUE TITLE
Test on different browsers & versions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#327]
According to Jill: *"At school I use internet explorer. At home chrome first then safari."*

**Comment by alexsoble** [comment]
Hmm.  We are already doing this... Can we narrow this issue down into something more specific?

**Comment by marimuraki** [comment]
We can close this. It was more a note to keep tabs on what browsers Jill said she is using --- and what other administrators / teachers / staff are using.
