### ISSUE TITLE
Add Notes section to profile

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#331]
Feature idea from conversation with Uri on Monday 11/2/15.

Add a section to the profile for miscellaneous notes that come up during Student Support Team meetings.

That way the flow looks roughly like this:

1. __Profile__: What does the student's past history look like?
2. __Notes__: What's the student's current status?
3. __Interventions__: What are we going to do to support the student in the future?

**Comment by marimuraki** [comment]
Jill's comments on notes:

- "Not every note may lead to an intervention but it could result in an intervention"
- "Teacher can use it as their own information tracking tool"

**Comment by alexsoble** [comment]
Closed via #353.
