### ISSUE TITLE
Generate report of students in interventions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#332]
Jill & Bridget spoke about how a report of students with interventions logged between [T, T+1] would be useful in SST & MTSS meetings where the team recaps with:

- **student** X will receive **intervention** Y by **educator** Z

**Scenario**

For example, suppose an SST occurred from 8:30-10:30 am and 15 students were discussed during this meeting. Currently, to recap, Jill would have to go into the profile of each student to refer to the interventions that were discussed and assigned. Instead, Jill would like to see a summary report e.g., list of all students discussed during that time period, what interventions were assigned, and who is responsible.

@jsgeiser @alexsoble: Please add any details that may be missing.

**Comment by marimuraki** [comment]
Another scenario: Referrals

- "I could see a case when you would print it out and use it for referral" - Jill

**Comment by jsgeiser** [comment]
Thank covers it - thansk!

**Comment by alexsoble** [comment]
This is a good feature idea. To work effectively it requires the SST/MTSS meeting flow to be optimized for capturing data from a UI point of view, which is work-in-progress: #373. Additionally, the new school overview page lets admins search for students by interventions. Closing this issue for now.
