### ISSUE TITLE
Add edit to interventions

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#333]
Add ability to edit interventions.

**Comment by marimuraki** [comment]
More context:

Currently once an intervention is saved, the input cannot be edited or deleted. Including the ability to edit and delete saved text will be key so that users can edit / delete incorrect information, add information within a specific prior input, etc.

**Comment by marimuraki** [comment]
@alexsoble: When editing an earlier intervention, it would be useful to direct the view to the intervention box rather than the user having to scroll back up each time. At first, I was also confused as what the behavior was when I clicked an intervention as I did not see what was happening outside of my view.

See gif below.

![licecap_smvtt_intervention_edit](https://cloud.githubusercontent.com/assets/1334815/12237958/3fd1b87e-b836-11e5-824f-c7953ab0433a.gif)

**Comment by alexsoble** [comment]
Covered in https://github.com/studentinsights/studentinsights/issues/5.
