### ISSUE TITLE
Indicate intervention saved

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#334]
Pulling this out separately as an issue from #312 @alexsoble: Comments based testing interventions-interface-v2 branch

**Issue: Indicate intervention has been added**

I noticed this when Colette was adding interventions in V1. She kept on clicking on "Save" because it wasn't clear that the intervention was added.

I did the same thing because I wasn't sure if the intervention got saved or my internet was slow ... and so I kept on clicking "Save". I didn't want to save my input so I opened up a new window to see if my interventions went through ... and I saw this:

<img width="404" alt="screenshot 2015-10-22 12 44 30" src="https://cloud.githubusercontent.com/assets/1334815/10676446/11eea080-78bb-11e5-85e9-b423c104f022.png">

So my interventions were being saved but since I had no confirmation of this, I kept clicking (similar to what Colette did) and ended up with duplicates.

Jill also experienced this bug during the MTSS meeting. She did not see that her intervention was saved so kept on clicking again and again. When she refreshed her browser, there were multiple copies saved (#333).

**Comment by alexsoble** [comment]
I'm unable to replicate the bug on Chrome, Firefox, or IE. (Tested on IE 11 using Browserstack).

Let's try to replicate it on your laptop as soon as possible and open up the debugger so that we can see if any errors are popping up on intervention save.

Once we're able to replicate the error we'll be able to fix it. @marimuraki

**Comment by alexsoble** [comment]
We replicated the bug! 

It occurs whenever multiline input is entered into one of the text fields and the intervention is saved.

The Rails app responds by rendering a `create.js.erb
