### ISSUE TITLE
Attach documents e.g., referrals, progress monitoring

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#337]
Jill said that attaching documents would be helpful e.g., adding IEP referrals, progress monitoring reports, etc. 

@jsgeiser: Feel free to add more detail.

**Comment by jsgeiser** [comment]
Yes - that could be a word, excel, etc. doc or a picture (e.g. picture of a student work sample, DIBELS report, etc.)

**Comment by alexsoble** [comment]
Not in the current project plan but definitely a thing we want to tackle.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/24.
