### ISSUE TITLE
Redesign student profile page

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#373]
The graphs are the first thing the user sees – but they're not necessarily the most useful!

**Comment by alexsoble** [comment]
Design V1: profile redesign mockups.pdf

**Comment by alexsoble** [comment]
Design V1: [profile redesign mockups.pdf](https://github.com/codeforamerica/somerville-teacher-tool/files/105267/profile.redesign.mockups.pdf)

**Comment by kevinrobinson** [comment]
We're also investigating with John whether we can get student profile pictures, which appeared to be stored as blobs in Aspen.

**Comment by alexsoble** [comment]
Redesign V2! [profile redesign v2.pdf](https://github.com/codeforamerica/somerville-teacher-tool/files/113208/profile.redesign.v2.pdf)

**Comment by kevinrobinson** [comment]
Some WIP code is here: https://github.com/codeforamerica/somerville-teacher-tool/compare/master...kevinrobinson:feature/student-profile-v2-alpha?expand=1.  Updating local demo data will be helpful for this feature too, but current status is that it looks like this:

<img width="1420" alt="screen shot 2016-02-02 at 6 42 13 pm" src="https://cloud.githubusercontent.com/assets/1056957/12768307/ccc5b976-c9dc-11e5-907c-3225cbad27f5.png">

Some options for next steps:
-  Improve layout and styling for demographics section
-  Improve header styling
-  Build the interventions panel
-  Add tab selection by clicking on panels
-  Refactor and drop in MCAS charts from existing profile page
-  Refactor and drop in behavioral and attendance charts from existing profile page
-  Add rendering for notes
-  Add UI for adding a note, endpoint
-  Add rendering for new interventions
-  Add UI for adding an intervention, endpoint
-  Possibly run migration for notes / interventions (requires looking at real data)

**Comment by kevinrobinson** [comment]
FYI @erose, @madrigalbrian, @sentientmachine, @alexsoble, @bryanhirsch

I pushed some more commits with progress here to https://github.com/codeforamerica/somerville-teacher-tool/compare/master...kevinrobinson:feature/student-profile-v2-alpha?expand=1.  I'll be working on it more next week, including Tuesday at Code For Boston, aiming to ship a prototype for feedback next week and a trial run next Friday (unless we get another snow day :)).

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/.
