### ISSUE TITLE
Import X2 data

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#38]
Import data from Somerville Public Schools' X2 Aspen data warehouse. This will provide data to drive student profiles that help teachers understand their students' history (both academic and behavioral) to adjust teaching strategies and assign more effective interventions. 

Data to import:

+ [x] Student names
+ [x] Student homerooms
+ [x] Home language 
+ [x] Attendance events (tardies, absences)
+ [x] Behavior events (suspensions, office visits)
+ [ ] Parent contact info (so that teachers can contact parents easily to take action on what they see)
+ [x] MCAS

Part of Epic #25.

**Comment by marimuraki** [comment]
Import MCAS data from X2's [student_assessment, assessment_definitions] table instead of Edwin Analytics --- via Uri Harel.

**Comment by marimuraki** [comment]
After talking to Uri and the teachers, we understand the importance of pulling in **SPED, IEP, 504** data.

With Kenya's help, we were able to identify:

- `STD_504_STATUS` = 504 Status
  - Active
  - Exited
- `STD_FIELDB_047` = 504
  - Not 504
  - 504
- `STD_FIELDB_044` = Disabilities
  - Autism
  - Communication
  - Developmental Delay
  - Emotional
  - Health
  - Intellectual
  - Multi Disabilities
  - Neurological
  - Physical
  - Sensory/Deaf-Blind
  - Sensory/Hearing
  - Sensory/Vision
  - Specific LDs
- `STD_FIELD_042` = SPED Placement
  - 3-5 Inclusion
  - 3-5 Mod Student
  - 3-5 Separate
  - 502.1, 502.2, 502.3, 502.4, 502.4(i), 502.5, 502.6, 502.7, 502.8, 502.1
  - Compl Goals
  - Full Inclusion
  - None
  - Not Enrolled
  - Parent Reqst
  - Partial Inclusion
  - Private Residential
  - Private Separate
  - Public Residential
  - Public Seperate
  - Substantially Separate
- `STD_FIELD_046` = SPED Level of Need
  - 500
  - Does not apply
  - High
  - Low < 2
  - Low >= 2
  - Moderate

MassDoE definitions: http://www.doe.mass.edu/sped/iep/forms/pdf/PL3.pdf
Additional resources: https://www.understood.org/en/school-learning/special-services/504-plan/the-difference-between-ieps-and-504-plans

@alexsoble @AmirHadjihabib

**Comment by marimuraki** [comment]
Looking at 504 status for 'Active' students:

| STD_504_STATUS | STD_FIELDB_047 | %  |
| ------------- |:-------------:| -----:|
| NULL | NULL |  0.03%  |
| NULL | 504 | 0.16%  |
| NULL | Not 504 | 97.90%  |
| Active | 504 | 1.38% | 
| Active | Not 504 | 0.40%  |
| Exited | 504 | 0.12% |

So let's exclude `STD_504_STATUS' as it does not seem particularly informative and possibly incomplete (in terms of data collection).

**Comment by marimuraki** [comment]
Need to handle out-of-range assessment score values. @alexsoble 
 
**Observed MIN / MAX** *(excluding 0 values)*

| Assessment | Obs MIN | Obs MAX  | Actual MIN | Actual MAX |
| ---------------- |:------:| -------:| -------:| -------:|
| MCAS | 202.00 | 342.00 | 200 | 280 |
| STAR | 56.00 | 1347.00 | *TBD* | *TBD* |
| WIDA-ACCESS | 100.00 | 948.00 | *TBD* | *TBD* |

**SQL QUERY:**

SELECT
  MIN(ASM_SCALE_SCORE),
  MAX(ASM_SCALE_SCORE),
  SUBSTRING_INDEX(SUBSTRING_INDEX(ASD_NAME, ' ', 1), ' ', -1) as ASD_TEST
FROM student_assessment
LEFT JOIN assessment_definition
  ON student_assessment.ASM_ASD_OID=assessment_definition.ASD_OID
INNER JOIN student
  ON student.STD_OID=student_assessment.ASM_STD_OID
INNER JOIN school
ON student.STD_SKL_OID=school.SKL_OID
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_ID_STATE IS NOT NULL
AND STD_OID IS NOT NULL
AND ASM_SCALE_SCORE != 0
GROUP BY ASD_TEST;

**Comment by marimuraki** [comment]
More details for context, maybe to include in definition hover.

- `STD_FIELD_046` = SPED Level of Need
  - Low < 2: Less than 2 hours of special education services per week
  - Low >= 2: 2-5 hours of special education services per week
  - Moderate: 6-14 hours of special education services per week
  - High: 15+ hours of special education services per week

MassDoE definitions: http://www.doe.mass.edu/sped/iep/forms/pdf/PL3.pdf

**Comment by marimuraki** [comment]
Feedback from @jgeiser on important info to pull in from X2

- student address
- homeless status (Y/N)
- medical or legal alerts 

**Questions to follow-up with John**

- Ask John about FRPL change to economically disadvantaged

@alexsoble @AmirHadjihabib
