### ISSUE TITLE
Speed up rendering on school overview dashboard

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#383]
Splitting this issue out from #378.

+ https://github.com/codeforamerica/somerville-teacher-tool/issues/378#issuecomment-173748903
+ https://github.com/codeforamerica/somerville-teacher-tool/issues/378#issuecomment-173750887

**Comment by alexsoble** [comment]
__Benchmark:__

+ Data: Demo data, 30 students
+ Browser: Internet Explorer via Browserstack
+ 4 filters total across 2 categories: 
  + Homeroom: 101 and 102
  + STAR Reading: < 25th percentile and 25th - 50th percentiles

**Comment by alexsoble** [comment]
### Overview

Rendering is looking fairly snappy on Chrome and Firefox. I wanted to try to measure the impact of the previous commits on Internet Explorer, since:

* that is how our users experience the app, and
* the app will be slower on Internet Explorer

### Setup 

I used Browserstack to simulate IE 11. The experience was *extremely* slow. It was unusable before the performance refactor and barely usable afterwards. I hope this is due in part to the remote browser-within-a-browser nature of Browserstack. 

I suspect that is the case, because our partners at Somerville Public Schools reported that the filters were a bit slow, but not unusable, _before_ the refactor. 

Open to ideas for better ways to profile performance in Internet Explorer from a Mac. Any thoughts on this @kevinrobinson?

Using both versions of the code, I clicked three filters in one category on, then clicked them each off again, and then did the same for a second category.

### Results

__Before refactor (previous two commits):__
![before2](https://cloud.githubusercontent.com/assets/3209501/12516492/b3ca7f2c-c0fb-11e5-853f-004fecf127e2.png)
![before refactor](https://cloud.githubusercontent.com/assets/3209501/12516491/b3c5333c-c0fb-11e5-8617-392a474be0a0.png)

__After refactor (previous two commits):__

![after2](https://cloud.githubusercontent.com/assets/3209501/12516496/b98d3cec-c0fb-11e5-828e-2f803f2d76c2.png)
![after](https://cloud.githubusercontent.com/assets/3209501/12516495/b98c3112-c0fb-11e5-8e13-42aa32b4ac2c.png)

**Comment by kevinrobinson** [comment]
@alexsoble Woah, that's rough!  That's a really nice improvements over where we started, and the OR filters UX look great to me.

I just tried out BrowserStack (awesome!), and I'm seeing ~2sec latency on adding and removing filters on IE11 on a Windows 10 box.  So not quite as bad, but when I tried to profile I got lots of lag in the developer tools lag and "long running script" warning.

One thing we should try is swapping in the production build of React.  All those nice warnings in development mode (eg., missing 'key' attributes, missing props) are stripped out in the production build and there's a significant performance difference.  Right now the asset pipeline is minifying the development version of React.  You can see this in the console in production:

<img width="874" alt="screen shot 2016-01-22 at 5 13 53 pm" src="https://cloud.githubusercontent.com/assets/1056957/12524526/88e770e6-c12b-11e5-810d-50995bfffbe0.png">
There's a commit here that swaps in the rails-react gem that might be worth trying, or more simply we could just branch which asset is included based on Rails env: https://github.com/kevinrobinson/somerville-teacher-tool/commit/26c3931c410f8ff8fd58c5292d25277d033c2371.

So maybe we can try that next week, see where that gets us, and then if it's still too laggy we can look further.  It also might be useful to see if the computation, rendering of filters, or rendering of tables is contributing more to the slowdown (the table had [this hack](https://github.com/codeforamerica/somerville-teacher-tool/blob/master/app/assets/javascripts/components/school_overview_page.js#L200) in it initially to keep using the jQuery tablesorter, which we could improve on if rebuilding the table each time is too expensive).

Also, for background, do users prefer using IE11, or is there a technology or policy issue?

**Comment by alexsoble** [comment]
@kevinrobinson Thanks for pointing out the React development/production build fix. 

The school system generally seems to be a Windows/IE world. All the Somerville desktops and laptops I've seen have been Windows machines. Not sure if there are technology or policy issues at play.

**Comment by alexsoble** [comment]
@kevinrobinson I cherry-picked the react-rails commit, merged, and pushed to demo/production: https://github.com/codeforamerica/somerville-teacher-tool/pull/389

I think after these optimizations, the main awkward choke point is now on page load. We are making a whole bunch of database queries. Treating discipline incident counts like tardies and absences (i.e. computing them with a nightly task and storing to the database) will cut that number down by a lot.

Merging in the rest of the `experiment/star-scores` branch will take a bit more time because our work overlapped a bit. We both moved chunks of code out of the main file into more modular bits. I should have looked at your STAR scores branch more carefully before refactoring! But not a huge deal, it won't take a crazy long amount of time.

**Comment by kevinrobinson** [comment]
@alexsoble awesome!

For page load, I wonder if there's any value in precomputing the entire
response aside from interventions and notes.  Would that be simpler, or do
you think it's better to enable other similar queries to benefit from
precomputing individual fields?

And yeah, the STAR scores branch was more a design spike than anything
else, probably my bad for not communicating about it more first. :)  I can
help out with that this week too.

**Comment by alexsoble** [comment]
@kevinrobinson Agreed the precomputing is a good idea for the server side. On the client side we are looking good now, even in IE! :+1:
