### ISSUE TITLE
Figure out how to create permissions system using X2 data

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#388]
## The goal

Based on input from Somerville principals, teachers, and district admins, the app will need at least three different tiers of permissions:

+ ___Classroom teacher___: Can see students in his or her grade level (his or her homeroom, plus other homerooms in the same grade level at the same school)

+ ___School level admin or interventionist___: Can see all students in a her or his school

+ ___District level admin___: Can see all students in the district

Even more granular permissions would be nice to have: for example, an interventionist who can access specific grade levels at a specific school. However, this level of permissions does not seem like an absolute "must" at this point. We should implement the three tiers above before adding more complexity. 

## The data schema

Currently, the only source of data we have about educators is X2, Somerville's Student Information System. Relevant fields in X2's `staff` column are `staff_type`, `school`, and `homeroom`.

In theory, we should be able to create the permissions system described above with these fields. But the reality doesn't seem that simple...

## The data reality

There are several issues with the X2 educator data:

* ___Missing administrators___
  * My initial assumption was that all administrators would have an "administrator" staff_type in X2. That is not correct. For example, Uri Harel, the Elementary Curriculum Coordinator who has been championing this project, is not listed as an "Administrator" and has a `staff_type` of `NULL`. Mary Skipper, the district superintendent, does not appear in the X2 educators export at all.

* ___Missing staff_type___
  * Of the 89 staff at Healey School, only 7% have a `staff_type` value.
  * 37% have no `staff_type` but are assigned to a homeroom, so we can assume these are classroom teachers or have similar roles. 
  * That leaves 56% with no `staff_type` and no homeroom. Who are these staff members? I have an email in to @jsgeiser to find out more about who these staff members are.
  * If some of the 56% of staff members will need access to the app, we will have to find or create more data about them to make this work.

* ___Missing homerooms___
  * 3% of Healey school staff have a `staff_type` of Teacher but no homeroom data.

## Solutions

Different approaches (or combinations of approaches) we could use to tackle this and create the permissions system we want:

* ___Look into updating X2 data:___
  * There may be a reason why Uri isn't tagged as an Administrator that I don't understand yet. Same with Mary Skipper not appearing in the database But if not, we could update X2 so that it matches our current picture of who Somerville administrators are and what access level they should have.

* ___Look at other data sources:___
  * John Breslin mentioned other data sources about staff that we could investigate:
    * The HR department's Filemaker system
    * The EPIMS Staff Roster file
  * Downside: These data sources may not be able to do a nightly data link like we have with X2, so the data could fall out of date quickly.
  * Downside: Even if we could make an automated data link, that introduces more complexity and more points of failure. Better to have a single source of truth about educators if possible.

* ___Administrator dashboard:___
  * If we accept that there will always be some discrepancies between the universe of X2 and the Somerville school system in reality, it makes sense to give administrators a dashboard they can use to override X2 and grant access to users within their schools/district.
  * For example, X2 doesn't include the `staff_type` of a reading interventionist, so @jsgeiser could go to an admin panel to give that person school-wide data access or access to a particular classroom or set of classrooms. John Breslin and I discussed this idea.
  * Upside: Gives control to principals and admins, lets them fine-tune how they think things should work within their domain.
  * Downside: Has the potential to create conflicting versions of reality. For example, what if a principal overrides a teacher's status, and then that status changes? Which takes precedence, X2 or the admin dashboard?
  * Downside: Has the potential to be a chore. If we can import information automatically and reliably  instead of asking principals and admins to keep it up-to-date, that's the optimal approach.

**Comment by alexsoble** [comment]
According to @jsgeiser (principal of Healey School), many of the staff members with no staff type and no homeroom are "former employees who may be at another school or outside the district."

How can we distinguish between active employees and former employees? 

The staff members who Jill said are not longer employed at Healey school have `status` of "Active" in X2. That seems incorrect.

In the words of the Healey school secretary, "Once they go in, they're in.

**Comment by kevinrobinson** [comment]
@alexsoble This is a great thing to discover, sounds like there might be an opportunity to help improve the in-person processes here. :)  I wonder how if this impacts authorization for X2 sign-on as well?

**Comment by alexsoble** [comment]
@kevinrobinson Good questions!

**Comment by alexsoble** [comment]
X2 counts: 

Status | Count
--- | ---
Inactive | 849
Active (includes both active and inactive staff) | 877
nil | 8
FAKE | 1

Staff Type | Count
--- | ---
Administrator | 73 
nil | 1420
Counselor | 39
Secretary | 4 
Teacher | 47
Substitute | 9
 "" | 142
Department Head | 1

**Comment by alexsoble** [comment]
## Resolution

+ ___X2 data quality improvements!___    :blush:

  + Improving the quality of educator Active/Inactive data from X2 was not difficult
  + The Secretary at the Healey school could just go into X2 and updated all of the staff's statuses
  + Secretaries don't necessarily do that for non-homeroom teachers because X2 is not the real source of work assignments or reporting about non-homeroom teachers, that's EPIMS

+ ___What we won't get from X2...___    :confused: 

  + Information about the staff type, work assignments, and other important data about Somerville staff who aren't homeroom teachers can't be found in X2
  + That information lives in other data sources: EPIMS and HR Filemaker
  + Neither integrate with X2
  + Data quality is low and a long chain of human processes is involved in using these systems

+ For now, punting on all of these issues by adding information about staff roles and permissions directly into the database with a private seed task
