### ISSUE TITLE
Fully productionize STAR change-over-time graphs

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#413]
+ [ ] Add STAR math
+ [ ] Make it navigable
+ [ ] Some test coverage

**Comment by alexsoble** [comment]
Improve STAR reading demo data so we can test locally.

**Comment by alexsoble** [comment]
[ ] Add option to clear filters
[ ] Fix line interpolation issues

**Comment by kevinrobinson** [comment]
[ ] update charts to show homeroom names

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights.
