### ISSUE TITLE
Add note about test stdout log

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#415]

**Comment by kevinrobinson** [comment]
@alexsoble https://github.com/codeforamerica/somerville-teacher-tool/pull/428 took care of this.

**Comment by alexsoble** [comment]
No longer applies; reversed the stdout redirect with https://github.com/codeforamerica/somerville-teacher-tool/commit/254728831b8f5fb42295edb695a6d47e9b6b6905 in #435.
