### ISSUE TITLE
Improve roster responsiveness

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#42]
@marimuraki: "when you change the width of the window, the table contents do not adjust with the frame i.e., the table contents spill out"

Screenshot from demo roster:

![roster-not-responsive](https://cloud.githubusercontent.com/assets/3209501/7169516/160c1b3c-e37b-11e4-966d-00f57b991f29.png)

Let's use CSS media queries to make the roster look nice—and potentially show fewer data points—at small screen widths.

**Comment by alexsoble** [comment]
Experimenting with assigning people to issues! @AmirHadjihabib & I are going to collaborate on this. Too bad you can't assign multiple people to an issue. :person_frowning:

**Comment by AmirHadjihabib** [comment]
Relates to issue #76
