### ISSUE TITLE
Align warning labels on all screens

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#43]
This is how the warning label alignment looks on my screen (Chrome) — labels slightly below: 

![alex-roster-view](https://cloud.githubusercontent.com/assets/3209501/7169621/fffe95c6-e37b-11e4-94c4-876b54d34047.png)

This is how the warning label alignment looks on Amir's screen (also Chrome) — labels slightly above:

![amir-roster-view](https://cloud.githubusercontent.com/assets/3209501/7169640/40be958e-e37c-11e4-81bf-cdaf044fa505.png)
 
Let's figure out what's causing this discrepancy and fix it so that the warning labels are properly aligned no matter who's looking at them.

**Comment by marimuraki** [comment]
I viewed it on Firefox and it looks like the above image --- warning labels below center.
