### ISSUE TITLE
Fix issue with Mixpanel current_educator on profile page

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#434]
JavaScript breaks on student profile page in production.

Message: 
> Uncaught TypeError: Cannot read property 'id' of undefined

The JS it's referencing is the Mixpanel Utils, but the error doesn't have to do with Mixpanel Utils.

The profile page dumps out inline JSON to be consumed by the front-end, which includes `Educator.all`.

Looks like the educator email addresses being printed detected by Cloudflare are replaced by something this:

`<a class="__cf_email__" href="/cdn-cgi/l/email-protection">[email&#160;protected]</a>`

Turning the Cloudflare automating email redaction off should fix the bug.

**Comment by kevinrobinson** [comment]
wow, that is an insane default!  is this something that's just configurable in the Cloudfare UI?

**Comment by alexsoble** [comment]
@kevinrobinson Hopefully! 

Currently Googling: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=turn+off+cloudflare+email+protection

**Comment by alexsoble** [comment]
@kevinrobinson Turned it off from the Cloudflare UI, waiting for the change to take effect.

**Comment by alexsoble** [comment]
Cloudflare protection off. Looks like I misidentified the issue because the Mixpanel JS error is still there.

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights.
