### ISSUE TITLE
Test with Internet Explorer

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#44]
We know that most teachers and staff at Somerville Public Schools use IE as their browser at work, so we need to test the app on Internet Explorer to make sure it looks the way we want it to look.

**Comment by AmirHadjihabib** [comment]
Tested on Sauce Labs app.

### Windows XP and IE8
![screen shot 2015-04-15 at 2 47 25 pm](https://cloud.githubusercontent.com/assets/4615904/7169946/09ab79b0-e37f-11e4-940b-8169ce7d499b.png)

Doesn't work: 
+ Dropdown styling
+ Circle rendering

### Windows 7 with IE9
![screen shot 2015-04-15 at 2 51 34 pm](https://cloud.githubusercontent.com/assets/4615904/7169977/2818bc5a-e37f-11e4-8230-d372cff0b85a.png)

Doesn't work: 
+ Dropdown styling

**Comment by alexsoble** [comment]
^ @bsmithgall You were right :disappointed:

**Comment by bsmithgall** [comment]
![sigh](https://31.media.tumblr.com/f26f23be7d1a572d8e509584c9b9889d/tumblr_moks5gh6OH1qjjhbco5_r2_250.gif)

**Comment by AmirHadjihabib** [comment]
Talked to John Breslin(Somerville Public School District IT) about what teachers have access to on their computers.

"On site here it's all IE, mostly 10 or 11. 
Resolution is 1280x1024 or 1024x768"
