### ISSUE TITLE
Refactor results display logic into a StudentResultPresenter

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#45]
Student results need their own presenter class! Sometimes a given result exists, sometimes it doesn't, but either way we need to handle the display logic gracefully in our roster view.

**Comment by alexsoble** [comment]
Otherwise we get not fun errors like these! 

![undefined-method](https://cloud.githubusercontent.com/assets/3209501/7171849/f1596cbe-e392-11e4-9e00-de0e52f5dfb6.png)

**Comment by alexsoble** [comment]
Now our app knows how to handle "N/A" results:

![handle-na](https://cloud.githubusercontent.com/assets/3209501/7172494/b4a8601c-e39d-11e4-84b2-a430e8482875.png)

**Comment by marimuraki** [comment]
Can we change "N/A" to "-"? "N/A" looks too similar to "NI".

**Comment by alexsoble** [comment]
Good point! I like it.

**Comment by alexsoble** [comment]
![dashes-are-cool](https://cloud.githubusercontent.com/assets/3209501/7186739/d02fdd00-e420-11e4-8224-823f1cb302cb.png)

**Comment by marimuraki** [comment]
Looks much cleaner! Loving it.

**Comment by alexsoble** [comment]
:blush: :blush: :blush:
