### ISSUE TITLE
Import X2 attendance (excused/unexcused)

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#47]
Import attendance data from X2 for student profile. Related to #38 #25.

**Comment by alexsoble** [comment]
Thank you @marimuraki for the data QA on this import! :+1:

**Comment by marimuraki** [comment]
Do we have an indicator for whether the absence is **excused** vs **unexcused**? Per Nicole's feedback, excused absences may not be counted towards risk as (much as) unexcused absences.

**Comment by alexsoble** [comment]
We have an ATT_EXCUSED_IND column. Out of 1,772,100 attendance events, 78,135 (4.4%) were excused. 

Also of interest: ATT_CODE_VIEW, ATT_DISMISSED_IND, ATT_REASON_CODE, ATT_COMMENT

**Comment by alexsoble** [comment]
Attendance import is functional and happening on a nightly basis. Still need to handle some irregularities and questions about the attendance data model, issue documented here: #96
