### ISSUE TITLE
Explain the data (key, legend)

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#52]
Good feedback from Kenya, data analyst at Somerville Public Schools: 

+ Need to explain that the red dots are warning indicators (maybe with a legend) 
+ Need to explain where the data is coming from and what it should be used for (maybe with a short paragraph at the bottom)

**Comment by marimuraki** [comment]
- [ ] Need to explain how risk levels are defined
- [ ] Need to explain colors: red, orange/yellow, green
- [ ] Need to explain data source
- [ ] Need to explain data date
- [ ] Need to explain acronyms e.g., what is IRL?
- [ ] Need to explain how to interpret data e.g., what is Instructional Reading Level?

**Comment by alexsoble** [comment]
@marimuraki: good list! :+1:

**Comment by alexsoble** [comment]
From our April 27 call with the wonderful Healey teacher team:

“What’s IRL? I guess that’s reading level...”

We need to be more careful about our assumptions around acronyms.

**Comment by AmirHadjihabib** [comment]
We had this in an early design. Might want to revisit it.

![screen shot 2015-04-27 at 10 49 15 am](https://cloud.githubusercontent.com/assets/4615904/7353783/1dd7e964-eccb-11e4-8c3d-97f398f4f5e8.png)

**Comment by marimuraki** [comment]
@AmirHadjihabib I like that hover design.

**Comment by marimuraki** [comment]
Feedback from Uri Harel on "at-risk" levels to highlight:
- growth < 40
- percentile < 40
- attendance < 90
- IRL more than a grade level behind

**Comment by AmirHadjihabib** [comment]
Add a key to the design.

http://invis.io/TR2X8FG2H

![roster phase 1 key - hover](https://cloud.githubusercontent.com/assets/4615904/7522127/05d71aa8-f4a8-11e4-87d5-9ffa39133954.png)

**Comment by alexsoble** [comment]
Looks :+1: :+1: :+1: to me.

**Comment by AmirHadjihabib** [comment]
### Tooltip key on hover

![tooltip](https://cloud.githubusercontent.com/assets/4615904/7539401/97b26adc-f55b-11e4-9ecf-cf1784d9ff2a.gif)
