### ISSUE TITLE
Integrate STAR data into roster front-end

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#55]

**Comment by alexsoble** [comment]
Current status: 

![star-roster](https://cloud.githubusercontent.com/assets/3209501/7325480/4d26c762-ea73-11e4-8de5-3d4446f3c348.png)

**Comment by marimuraki** [comment]
Check STAR & MCAS administration dates.

- **STAR**: [date_taken]
  - Raw data files unique by [student_id, date_taken] i.e., multiple assessment results per student by test date  
- **MCAS**: March/April
  - How are you pulling in re-tests? Are you taking the first or most recent (to account for retests) MCAS assessment result?

**Comment by alexsoble** [comment]
Ah, thank you @marimuraki!

+ __STAR__: Will add date_taken as an attribute and assign on import. 
+ __MCAS__: Not pulling in retests at all right now.

**Comment by alexsoble** [comment]
### What this looks like

GIF:

![star-mcas-select](https://cloud.githubusercontent.com/assets/3209501/7327611/80033fca-ea83-11e4-89b0-18c3ca714b0c.gif)

**Comment by marimuraki** [comment]
Will you build in search by subject e.g., search for "Math" shows STAR Math and MCAS Math?

**Comment by alexsoble** [comment]
@marimuraki All about what we decide to prioritize as a team! Let's discuss together on Monday. We should also figure out what we want to learn from our Healey teacher friends by showing them this prototype. That will help us set priorities.

**Comment by alexsoble** [comment]
Yesterday we demoed the roster with STAR data for the Healey 5th grade team. Successor issues are #56 (richer data) and #59 (more flexible sorting).
