### ISSUE TITLE
Import free/reduced lunch status

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#60]
From our April 27 call with the wonderful Healey 5th grade teacher team:

"can you put a free/reduced lunch category in here?"

**Comment by marimuraki** [comment]
@alexsoble: `stdFieldB031` in STUDENT table

**Comment by alexsoble** [comment]
Not really fixed! Upon closer inspection, free/reduced lunch status is not actually part of the profile design. Part of the roster design, though.
