### ISSUE TITLE
Update "about" page

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#61]
On our April 27 call with the wonderful Healey teacher team, the first question we got when we shared the link to http://www.somerville-teach.tools/ was:

“What is this?"

The homepage should better explain what this tool is and who it's for.

**Comment by alexsoble** [comment]
@AmirHadjihabib, can you give this a look and maybe make the "about" page stronger before we close the issue? The current "about" page is very text-heavy. It's also serving as the landing page for new users. Wondering how we could make it more clean & visual. The CSS could use a little love too I think. You can view it at https://www.somerville-teach.tools.

**Comment by AmirHadjihabib** [comment]
Sweet I will check it out.

**Comment by marimuraki** [comment]
@AmirHadjihabib Share your about page re-design!

**Comment by AmirHadjihabib** [comment]
Here is the current design. 

http://invis.io/DB2WEV84R

![about page](https://cloud.githubusercontent.com/assets/4615904/7497718/3497e610-f3d1-11e4-8df5-f8bc069b45e7.png)

**Comment by alexsoble** [comment]
@AmirHadjihabib — looking so beautiful! The coded version and the design both!

**Comment by AmirHadjihabib** [comment]
Thanks @alexsoble! All your help made it happen.

**Comment by alexsoble** [comment]
:heart_eyes: :heart_eyes: :heart_eyes:
