### ISSUE TITLE
Integrate ACCESS data

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#65]
Given the large ELL student population in Somerville, ACCESS (Assessing Comprehension and Communication in English State-to-State for English Language Learners) is an important measure of performance for this subgroup.

"Federal and state laws require that English language learner (ELL) students be assessed annually to measure their proficiency in reading, writing, listening, and speaking English, as well as the progress they are making in learning English. In fulfillment of these laws, ELL students are required to participate in ACCESS for ELLs tests."

Timeline of administration:
- January-February every year

http://www.doe.mass.edu/mcas/access/

**Comment by marimuraki** [comment]
Referrals to SPED should include ELL ACCESS data, when relevant. -- M.D.

**Comment by marimuraki** [comment]
@alexsoble: Since we have X2 assessment exports which include ACCESS, I want to ping this issue again given the importance and value-added of capturing how subgroups of students e.g., English Language Learners (ELL) are performing. 

Somerville has a large immigrant student population --- and as many of our community partners / parents / teachers have said, supporting those children who are most in need is key. ELL students are at higher risk of falling behind in literacy / reading proficiency. If we only use MCAS and STAR assessments, we will not fully capture this subgroup.

**Somerville ELL Stats**
- Spring 2012 MCAS only 7% of the ELLs proficient!

Reference: IES Resubmit_FINAL

**Comment by alexsoble** [comment]
@marimuraki -- Agreed. Could you take a look at the ACCESS data to see if any questions surface, like how to find growth levels when we were pulling MCAS? Then let's work with @AmirHadjihabib on the front end designs for how we will visualize and use ACCESS information. Then we'll import from X2.

**Comment by marimuraki** [comment]
@alexsoble: ACCESS is in the current X2 assessment export under `assesment_test` = **WIDA-ACCESS**

Agree. I will look at the ACCESS data and see what values we need to clean & map to represent in the roster.

**Comment by marimuraki** [comment]
**Feedback from Uri**

- [ ] Getting ACCESS (ELL) scores in there and pulled from X2

**Comment by marimuraki** [comment]
On my TODO to understand the ACCESS data and work with @AmirHadjihabib to mock up what teh tables / graphs would look like & pull in data with @alexsoble

**Comment by marimuraki** [comment]
"The range of possible scale scores for the entire battery of ACCESS for ELLs forms, Kindergarten through grade level cluster 9-12 is 100-600. However depending on the tier and grade level, each form has a different range of possible scale scores that fall within this 100-600 range. For example, the Kindergarten ACCESS for ELLs test form only has a possible scale score range of 100-400."

Resource: https://www.wida.us/assessment/access/scorereports/access_interpretive_guide11.pdf

**Comment by marimuraki** [comment]
Valid score ranges: 
- [100, 400] : Kindergarten
- [100, 600] : Grades 1-12 

Need to handle out of range values:
- < 100
- > 400 for Kindergarten
- > 600 for Grades 1-12

@alexsoble

**Comment by marimuraki** [comment]
[Spring 2015 ACCESS Interpretive Guide for Score Reports](https://www.wida.us/get.aspx?id=25) plus general [information](https://www.wida.us/assessment/access/)

**Five Grade Level Clusters**: Kindergarten, 1–2, 3–5, 6–8, and 9–12
"Within each grade-level cluster (except Kindergarten), ACCESS for ELLs is divided into three overlapping tiers: A (Beginning), B (Intermediate), and C (Advanced) to best represent the entire range of English language proficiency for this diverse student population."

Scale Scores **Vertically Scaled!** :+1: 
- "It is vertically scaled across tiers and grade-level clusters so that interpretation of scores is identical across grades. This means that scores can be compared across grade level clusters and tiers."

Scale Scores **Not Comparable across Domains**
- "With the vertical scale, scale scores across grades can be compared to one another within (but not across) a language domain (Listening, Speaking, Reading, or Writing). Each domain has a separate scale; therefore, a scale score of 300 in Listening is not the same as 300 in Speaking."

Proficiency Levels: **Interpretive Scores"
- 1-Entering, 2-Emerging, 3-Developing, 4-Expanding, 5- Bridging, and 6-Reaching
- "Proficiency level scores are presented as whole numbers followed by a decimal. The whole number indicates the student’s language proficiency level as based on the WIDA ELD Standards. The decimal indicates the proportion within the proficiency level range that the student’s scale score represents, rounded to the nearest tenth."

Proficiency Levels: **Grade-Specific** and other Key Characteristics
- "They are interpretations of grade level specific (not grade- level cluster) scale scores."
  - "For example, a Reading scale score of 303 for a fifth grade student will be interpreted as PL 2.0. The same scale score for a fourth grader will result in PL 2.5, and for a third grade student that scale score will result in PL 3.1."
- "The interpretation of scale scores to PL scores is domain specific."
  - "Each domain reports a separate score; therefore, the same scale score in Listening and Reading will not become the same PL score. For example, for a sixth grade student in Grade-level Cluster 6–8, a scale score of 380 for Listening becomes a PL score of 5.0, while a scale score of 380 for Reading becomes a PL score of 5.9."
- "They describe student performance based on six ELP levels."
- "The Literacy, Oral, Comprehension, and Overall (or Composite) PLs are derived from the scale scores for the domains, not the PL scores."
- "To monitor growth over time, it is recommended to use scale scores and not the PL scores."

@alexsoble @AmirHadjihabib: A lot of nuances! :smile:

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: We have WIDA ACCESS for 2013, 2014, 2015.  

`tab assessment_test school_year if assessment_test == "ACCESS" | assessment_test == "WIDA-ACCESS" | assessment_test == "W-APT", m`

| Test |  2013 | 2014 | 2015
| ------------- |:-------------:| -----:| -----:|
| ACCESS | 0 | 0 | 6,624
| W-APT | 75 | 380 | 381
| WIDA-ACCESS | 4,144 | 5,329 | 1
Total | 4,219 | 5,709 | 7,006

**Summary / Takeaways**
- In X2, the `assessment_test` values changes from "WIDA-ACCESS" to "ACCESS". Make sure to include observations under both `assessment_test`. 
- Other data issues
  - `assessment_scale_score` is messy! :sob: We need to:
    - clean up `assessment_performance_level` values in the `assessment_scale_score` variable into the `assessment_performance_level` variable
      - If 1 <= value < 7, move score to `assessment_performance_level` and replace to missing in `assessment_scale_score`
      - 0 values?
  - `assessment_performance_level` is messy! :sob: 
    - clean up the numerical vs. categorical string values for performance levels based on the mapping 1-Entering, 2-Emerging, 3-Developing, 4-Expanding, 5- Bridging, 6-Reaching
      - e.g., Entering 1, Entering, 1 Entering, etc >> 1
- Should we include ["W-APT"](https://www.wida.us/assessment/W-APT/), the ACCESS Placement Test? I'd say exclude for now and just focus on including ACCESS.

**Comment by marimuraki** [comment]
"Raw scores are reported for Comprehension, Speaking, and Writing. Scale scores and proficiency levels are reported for the four language domains (Listening, Speaking, Reading, and Writing) and four different combinations of language domains. These combinations include: Oral Language (Listening and Speaking), Literacy (Reading and Writing), Comprehension (Listening and Reading), and Overall or Composite Score (a combination of all four language
domains)."

Ask teachers what domains they would like to see: separate language domains or combinations domains. 

**Mock-up**
- @AmirHadjihabib and I will use the 4 individual language domains + overall: Listening, Speaking, Reading, Writing, Overall.
- Include only show scale scores ... for simplicity since ACCESS scores are already confusing e.g., not comparable across domains

@alexsoble: Sound good?

**Comment by marimuraki** [comment]
@alexsoble: check it out https://projects.invisionapp.com/share/ZA3KC8FGN#/screens

**Comment by marimuraki** [comment]
@alexsoble @AmirHadjihabib: We will also need to pull in MEPA and MELA-O assessments to capture a complete picture of ELL students' performance. MEPA and MELA-O were replaced by ACCESS (similar to how MAP was replaced by STAR).

*"ELL students are required to participate in ACCESS for ELLs tests, which replace MEPA tests, beginning in the 2012-2013 school year"* ([link](http://www.doe.mass.edu/mcas/access/))

**Comment by marimuraki** [comment]
@alexsoble: We need to be careful when pulling in ACCESS. The `assessment_subject` does not capture the subject well. 

Currently we are only planning to show OVERALL ACCESS scores. So we will need to parse the `assessment_name` to identify the "Overall" and "Composite" rows.

assessment_name | assessment_subject | assessment_test
------------ | ------------- | ------------- 
WIDA-ACCESS 2013 Winter Speaking  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Comprehension | ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Reading | ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Literacy  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Oral  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter *Composite  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Listening | ELL |  WIDA-ACCESS
WIDA-ACCESS 2013 Winter Writing | ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Reading | ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Comprehension | ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Writing | ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Speaking  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter *Composite  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Oral  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Literacy  |  ELL |  WIDA-ACCESS
WIDA-ACCESS 2014 Winter Listening | ELL |  WIDA-ACCESS
ACCESS 2015 Winter Comprehension  |  ELL |  ACCESS
ACCESS 2015 Winter Literacy | ELL |  ACCESS
ACCESS 2015 Winter Writing  |  ELL |  ACCESS
ACCESS 2015 Winter Oral | ELL |  ACCESS
ACCESS 2015 Winter Speaking | ELL |  ACCESS
ACCESS 2015 Winter *Overall | ELL |  ACCESS
ACCESS 2015 Winter Listening  |  ELL |  ACCESS
ACCESS 2015 Winter Reading  |  ELL |  ACCESS

**Comment by alexsoble** [comment]
Areas of work:

+ [ ] Further data quality investigation
+ [ ] Talk to ELL teachers to gain more domain understanding
+ [ ] Incorporate into school overview dashboard for principals
+ [ ] Deploy more intelligently within student profile
  + i.e. if student is Limited English proficient, ACCESS data over time is essential
+ [ ] This will be included in SPED referral work #100

**Comment by alexsoble** [comment]
One more area of work via @marimuraki https://github.com/codeforamerica/somerville-teacher-tool/issues/301#issuecomment-154191073:

> Break down into domains:
> - Listening
> - Speaking
> - Reading
> - Writing

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/16.
