### ISSUE TITLE
Understand data release timelines

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#66]
Understand the process of MCAS & STAR data releases:

- When is the data released?
- What assessment date is linked to each data release? #56
- What are the file names (is there are systematic naming convention)?

**Comment by marimuraki** [comment]
Broad timeline:

- July: Preliminary MCAS available
- August: Final MCAS available
- September (early): DIBELS/STAR testing
- September (late): STAR data available
- September (late): FALL ROSTER DISTRIBUTED 
- October (early): X2 data snapshot
- October (mid): DIBELS data available
- January: DIBELS/STAR testing
- January-February: WIDA ACCESS 
- January (late): STAR data available
- February (early): X2 data snapshot
- February (early): DIBELS data available
- February (mid): WINTER ROSTER DISTRIBUTED 
- March-April-May: MCAS testing
- April-May: DIBELS/STAR testing
- May (early): X2 data snapshot
- May (mid): STAR & ACCESS data available
- June (early): DIBELS data available
- July (mid): Preliminary MCAS data available
- August (mid): Final MCAS data available

**Comment by alexsoble** [comment]
@marimuraki — Is this still an open issue? Should we add this info somewhere in the repo?
