### ISSUE TITLE
Red dots

### ISSUE THREAD

**Issue by DanielHadley** [codeforamerica/somerville-teacher-tool#70]
Tool looks great so far. I like the minimal design. I'm sure the red dots have some significance, but I could not understand it right away. Is there a key to understand those?

**Comment by alexsoble** [comment]
This is an excellent point. Falls under #52. The dots represent pieces of data that mean "warning." We really need to :arrow_up: our explanations of the data! Thanks for adding this comment @DanielHadley. :blush:
