### ISSUE TITLE
Export student profile

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#72]
**How can the student profile be used by teachers and administrators?**

Uri Harel said that the student profile would be useful as part of the student referral i.e., *“I can print it out and that can be my student referral”*

Let's build a feature to:
- export the student profile into PDF, CSV, Excel to be saved, printed, etc

**Comment by jsgeiser** [comment]
I agree with this. Would this include any academic data? In other words, could there be an option to print-out a report of academic data (MCAS, STAR, DIBELS) either current or past that could be given to parents? Could the teacher print out a report for parents and select the data points they want?

**Comment by marimuraki** [comment]
Great idea @jsgeiser! The teachers mentioned how including functionality to export the student roster table -- which includes current assessments (MCAS, STAR, etc) --- into a CSV file would be helpful to let them, for example, 1) do their own visualizations/analyses in Excel and 2) print out to share with parents. 

The student profile would include behavior information and also historical academic information so, yes, the idea is that it could be printed out as a report. The idea of being able to select specific data points is a great one and something we will keep in mind.

**Comment by alexsoble** [comment]
Plotting out loud for tonight's Code for SF brigade meet-up — this would be a great, modular kind of function that a brigade member might be able to help us with.

**Comment by peterjeliot** [comment]
Even better than .pdfs, in my opinion, is the ability to just print the page directly. You can use `@media print {}` CSS for what the page should look like printed.

Main downside is that people don't expect pages to be printable, but you can add a "print this page" link:

```
<a href="javascript:window.print()">Print this page</a>
```

This doesn't address if they *really want* a PDF they can save for later, then print. Unless they use a mac, in which case "print to PDF" is a built-in feature (it's a fake printer driver).

**Comment by alexsoble** [comment]
@peterjeliot — Most of the machines we've seen in the Somerville Public School district are Windows.

@jsgeiser — What do you think about Peter's suggestion? Is the main use case to print, or is there additional value in having a PDF output that can be saved for later? 

We will also ask the teacher teams we're going to meet with on Tuesday next week what their preferences / priorities are!

**Comment by peterjeliot** [comment]
The print view for /students/# looks fairly clean right now, if a little wasteful of space. The only broken part is that the graph (generated by HighCharts) resizes using JS instead of CSS for some reason. Print views don't have JS, so it gets sized a little wrong. The graph is scaled for whatever size the window was when you hit print.

**Comment by jsgeiser** [comment]
Yes, Somerville uses windows although plenty of staff bring in mac's and use the wireless. There is benefit to printing the webpage and allowing the user to pick what they want printed. One reason for a PDF may be if a teacher wants to email a data page to someone (another teacher, parents, etc.). Could you do that with the "print this page" feature? Would that be "email this page" kind of thing?

**Comment by alexsoble** [comment]
Hi @jsgeiser and @peterjeliot!  

Today we talked with the Healey 5th grade teacher team to get more clarification here.  They described two main use cases:

* Exporting the data as an ***Excel file*** to perform custom analysis. Excel seems preferred over CSV because not everyone in the teacher group was familiar with the term CSV. This discussion was in the context of the roster (#87) but probably applies to both.
* Exporting the data as a ***PDF file*** in order to email the summary to their teacher team or the principal (@jsgeiser, this is exactly what you mention above).

It would be excellent to turn these actions into UX elements on the site — a button that says "Email PDF to Teacher Team" / "Email PDF to Principal" and then populates a new email with the file attached and the to: field autocompleted.

Since we aren't systematically exporting details about teacher email addresses, principal email addresses, or teacher/classroom relationships yet, I think the immediate next step is to simply have two buttons: one "Export to Excel" and one "Export to PDF". 

cc @AmirHadjihabib for design input

**Comment by jsgeiser** [comment]
This sounds good. I like the option for either exporting to excel to be able to move data around or to PDF as a summary sheet. Thanks!

**Comment by AmirHadjihabib** [comment]
Here are the designs

![student export 1](https://cloud.githubusercontent.com/assets/4615904/8553962/fba476a6-24b4-11e5-913d-0faf21def696.png)

![student export 2](https://cloud.githubusercontent.com/assets/4615904/8553966/033492ca-24b5-11e5-99df-557a6e80d436.png)

**Comment by alexsoble** [comment]
@AmirHadjihabib — Looks good!

**Comment by griggsca91** [comment]
For the excel exporting, at the moment, would it just be best to have it return an excel file with just a dump of the CSV export in there?

**Comment by marimuraki** [comment]
@griggsca91: that make sense!

**Comment by marimuraki** [comment]
Feedback on export: **Include student name / ID** in the export either in the sheet or as the filename.

Currently the CSV export, exports to a file named "export.csv". There is no information in the file that indicates which student the data belongs to. If a teacher downloads multiple students' profile data, s/he will have e.g.,:

export.csv
export(1).csv
export(2).csv
export(3).csv
...

... and would not be able to differentiate the files.

@alexsoble @AmirHadjihabib: We should add a student identifier as either the file name or in the file content.

**Comment by marimuraki** [comment]
@AmirHadjihabib @alexsoble: Comments from Uri on **PDF print-out of student profile**

Uri liked the one-page printout but said that key information on behavior and interventions is missing.
- **Use case:** His vision of how the PDF will be used is in MTSS (multi-tiered system of support) school support team meetings, parent-teacher conferences, and SPED student referrals. For all these meetings, behavior and interventions are key.
- **Feedback:** Uri said if it takes a 2-page PDF to include all key information, it's ok and it can be printed double-sided. But more important than the number of pages is having the information that is needed to make student support / referral / etc decisions.

Amir's design: Also see #180 

https://www.dropbox.com/s/4w3tkxq8rflaznf/profile_export.pdf?dl=0

**Comment by marimuraki** [comment]
Currently we are  exporting a CSV with:
- attendance
- behavior
- MCAS
- STAR

We will need to build in:
- student information (most important) :star:
- DIBELS
- ACCESS

**Comment by marimuraki** [comment]
Added in demographics. Still need to add to CSV export:

- Student ID or name
- DIBELS
- ACCESS

Also, name export file by student ID.

**Comment by marimuraki** [comment]
@alexsoble: Another tweak now that the interventions module is included: the export button is confusing as it is specific to the profile, not the interventions module.

**TODO**: Only show **export** button on profile page. Related to #75.

<img width="1051" alt="screenshot 2015-10-27 16 02 30" src="https://cloud.githubusercontent.com/assets/1334815/10775356/e7664fee-7cc4-11e5-98d6-4b55ff2c156e.png">

**Comment by alexsoble** [comment]
There are several different features that fall under the umbrella of exporting a student profile, let's try to break that down a bit.

CSV export on student profile is functional. We can add DIBELS, ACCESS and other data points at a later time but that isn't a high priority for the project right now.

Exporting a SPED referral document from the profile is a high priority, tracked in this issue: #100
