### ISSUE TITLE
Integrate DIBELS data

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#73]
Integrate Dynamic Indicators of Basic Early Literacy Skills (DIBELS) for K-6 students.

**Comment by marimuraki** [comment]
@alexsoble: Now that we have X2 assessment, let's start looking at pulling in DIBELS for those students who are not eligible to take MCAS & STAR.

DIBELS is particularly important for the **early education** piece of Somerville's mission to support children from early on.

**Comment by alexsoble** [comment]
@marimuraki -- Since our immediate goal is to support Summer School, how should we prioritize this issue? Also -- before we write code to import, could you take a look at the data to see if questions surface, like how to find growth levels when we were pulling MCAS? Then let's work with @AmirHadjihabib on front end designs for how we will visualize and use the information.

**Comment by marimuraki** [comment]
@alexsoble: Similar to #65.

**Comment by marimuraki** [comment]
**Feedback from Uri**

- [ ] Getting DIBELS scores in there and pulled from X2

**Comment by marimuraki** [comment]
On my TODO to understand the DIBELS data and work with @AmirHadjihabib to mock up what teh tables / graphs would look like & pull in data with @alexsoble

**Comment by marimuraki** [comment]
In X2 student assessment table we have `assessment_performance_level` that captures DIBELS "Likely Need for Support" levels.

- Benchmark
- CORE / Core
- Check ISF
- Check ISF and PSF
- Check LNF
- Check LNF and NWF-CL
- Check NWF-CLS
- Check ORF
- Check PSF
- Check PSF and NWF-CL
- INTENSIVE / Intensive
- STRATEGIC / Strategic

The levels {Benchmark, Core, Intensive, Strategic} make up 99% of the observed performance levels.

Looks like Benchmark == Core for earlier years. More recent years, the levels are:

Based on [Kindergarten Benchmark Goals and Cut Points for Risk](https://dibels.uoregon.edu/docs/DIBELSNextFormerBenchmarkGoals.pdf).

- **Core**: Likely to need core support
  - Score level: At or above benchmark
- **Strategic**: Likely to need strategic support
  - Score level: Below benchmark
- **Intensive**: Likely to need intensive support
  - Score level: Well below benchmark

**TODO**: Need to check if these score and need levels differ across grades.

@alexsoble: Working with @AmirHadjihabib now to mock-up DIBELS in student profile.

Resource: https://dibels.uoregon.edu/docs/DIBELSNextFormerBenchmarkGoals.pdf

**Comment by marimuraki** [comment]
In more detail:

. tab assessment_year if assessment_test == "DIBELS" & (assessment_performance_level == "BENCHMARK" | assessment_performance_level == "INTENSIVE" | assessment_performance_level == "STRATEGIC" | assessment_performance_level == "CORE") 

Here is the tabulations for students with DIBELS who are currently ACTIVE.

| Year = substr(date, 1, 4) | # | %  |
| ------------- |:-------------:| -----:|
 2008 |  853 | 9.44
 2009 | 2,353 | 26.05
 2010 | 1,671 | 18.50
 2011 | 672 | 7.44
 2012 | 1,157 | 12.81
 2013 | 2,328 | 25.77

@alexsoble @AmirHadjihabib: We should ask Kenya about what might be going on here.

**Comment by marimuraki** [comment]
Here is the tabulation based on school year defined as August Y-1 to July Y. Again, these are for currently ACTIVE students.

| School Year | # | %  |
| ------------- |:-------------:| -----:|
       2009 |      2,379 |      26.33
       2010 |      2,498 |      27.65
       2012 |        672  |      7.44
       2013 |      3,485 |      38.58

**Comment by marimuraki** [comment]
Primary DIBELS values to pull out:

- Benchmark
- CORE
- Core
- INTENSIVE
- Intensive
- STRATEGIC
- Strategic
