### ISSUE TITLE
Export student roster

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#75]
Teachers have said how it would be useful to be able to export the student roster into:
- a CSV file to do their own analyses & visualization in Excel
- a report to show to parents at meetings

Related to #72

**Comment by marimuraki** [comment]
Both teachers and principals have said that an export of the roster to CSV or Excel #169 would be more useful than the export of the profile #72.
 - Data export
  - *"Can you export the Roster for the whole class, whole school?"*
  - *"As a teacher I would want to export all my student's data, not each student's data one at a time and have to compile 25 student files"*

**Comment by marimuraki** [comment]
@alexsoble: Let's remove the export button from the roster for now since it is not functioning and can be confusing.

![screenshot 2015-10-27 15 33 55](https://cloud.githubusercontent.com/assets/1334815/10774726/50ae8cc8-7cc0-11e5-8c36-af106600606b.png)

**Comment by alexsoble** [comment]
Will remove. Would be good to actually implement.
