### ISSUE TITLE
Show interventions in roster view

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#87]
## ToDo:

+ [ ] Design
+ [ ] Back-end
+ [ ] Front-end

https://github.com/codeforamerica/somerville-teacher-tool/issues/59#issuecomment-100472417

**Comment by AmirHadjihabib** [comment]
@jsgeiser Here is a version with interventions both on the Roster and the Profile. It would be great to hear your thoughts. You can comment directly on the design.

http://invis.io/TK2ZLZU97
Press "c" to comment and hold "shift" to see clickable areas.

Thanks!

**Comment by jsgeiser** [comment]
This is good - Thank you! I left a comment on second page with detailed data.

**Comment by AmirHadjihabib** [comment]
Awesome. Thank you for your feedback!

**Comment by kevinrobinson** [comment]
@alexsoble is working on cleaning up some tech debt related to the roster page, and that will block progress here until it's done.  It's on this branch: https://github.com/codeforamerica/somerville-teacher-tool/tree/refactor/use-same-interface-for-homerooms-and-schools.

After that, we can add a minimal UI for this, (eg., column showing count of interventions or name of top two interventions), similar to the dashboard overview page.

**Comment by kevinrobinson** [comment]
@AmirHadjihabib If you can re-share those Invision links that'd be cool, @alexsoble and I are getting 404s trying to reach them now.  No worries if not :)

**Comment by marimuraki** [comment]
@kevinrobinson, here you go! @alexsoble can provide more context since some of these might be older / newer iterations of the designs.

- Roster: https://invis.io/UM3M7Z7K3
- Roster: https://invis.io/VG5TVIS9M
- Profile: https://invis.io/ZA3KC8FGN
- Profile: https://invis.io/KW43V95BT

**Comment by kevinrobinson** [comment]
@marimuraki awesome, thanks so much! :)  yeah, @alexsoble and I are trying to do some triaging to figure out what's most important to focus on for the next iteration, so this is super helpful!

**Comment by marimuraki** [comment]
Great, I am happy to help where I can so feel free to cc' me if you are trying to track anything down from our CfA days. Love seeing all you & @alexsoble have been working on! :smile:

**Comment by kevinrobinson** [comment]
Yeah!  We'd love to share the plan for the next iteration if you're able at some point in the next week, and what we're thinking.  Regardless of whether you're still traveling the world then or busy with other projects your input would be super valuable. :)

**Comment by marimuraki** [comment]
I'm in! Depending on when next week, I will be in France, Israel, or Japan so let me know when and would love to learn what's new, planned, etc. :smile:

**Comment by kevinrobinson** [comment]
@marimuraki Awesome!  Moving coordination to email, and inviting @AmirHadjihabib to the party too if he's around and interested. :)

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights/issues/18.
