### ISSUE TITLE
Make fake data more realistic using aggregates

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#94]
* How many absences does the average Somerville student have per year?
* How many tardies does the average Somerville student have per year?
* How many discipline incidents does the average Somerville student have per year?
* ... and other broad stats that can make our fake data more realistic and a better fit with the real thing

**Comment by marimuraki** [comment]
- For students **with** absences, the average number of absences in ~9. 

School Year | Avg. Absences
------------ | -------------
2007 | 8.9
2008 | 8.5
2009 | 8.9
2010 | 8.3
2011 | 8.5
2012 | 8.1
2013 | 8.9
2014 | 9.1
2015 | 8.8

`school_year` generated using `event_date` where school year is defined from August `calendar_year`-1 through July `calendar_year`. Excluding out-of-range `event_date`. Basic stats available for `school_year` [2001, 2015].

**Comment by marimuraki** [comment]
- For students **with** tardies, the average number of tardies is increasing to ~12 in most recent years. 

School Year | Avg. Tardies
------------ | -------------
2005 | 9.3
2006 | 7.9
2007 | 7.1
2008 | 7.3
2009 | 6.4
2010 | 7.4
2011 | 8.4
2012 | 9.5
2013 | 11.2
2014 | 13.2
2015 | 11.9

`school_year` generated using `event_date` where school year is defined from August `calendar_year`-1 through July `calendar_year`. Excluding out-of-range `event_date`. Basic stats available for `school_year` [2001, 2015].

**Comment by marimuraki** [comment]
Note that these numbers are based on currently **active** students and does not include students who were enrolled in a given year but are no longer enrolled. @alexsoble: correct?

**Comment by marimuraki** [comment]
- For students **with** behavior incidents, the average number of incidents is ~5-6. 
- **Note**: Includes only **active** students --- not historical information on all students in a given school year.

School Year | Avg. Incidents | Students
------------ | ------------- | -------------
2007 | 1.6 | 20
2008 | 1.6 | 28
2009 | 1.7 | 43
2010 | 2.0 | 35
2011 | 2.7 | 79
2012 | 3.6 | 131
2013 | 7.0 | 163
2014 | 6.0 | 311
2015 | 5.2 | 361

- For 2015, including only students with non-zero incidents:

Stat | Value
------------ | -------------
N | 361
mean | 5.2
sd | 8.3
min | 1
max | 95

`school_year` generated using `event_date` where school year is defined from August `calendar_year`-1 through July `calendar_year`. Excluding out-of-range `event_date`. Basic stats available for `school_year` [2001, 2015].

**Comment by alexsoble** [comment]
@marimuraki -- awesome, thank you!

One follow up, what percent of students have zero attendance / tardy events?

**Comment by marimuraki** [comment]
School Year | Absent | Tardy | N
------------ | ------------- | ------------- | -------------
2015 | 94% | 69% | 4823

So:
- only ~6% of active students are never absent in 2015
- ~31% of active students are never tardy in 2015

**Comment by alexsoble** [comment]
Thank you @marimuraki!

**Comment by alexsoble** [comment]
Plotting out loud for tonight's Code for SF brigade meet-up — since this issue is about demo data, it would be a fantastic thing to do together with brigade members.

The relevant files:

somerville-teacher-tool > db > seeds > demo > demo_data > fake_student.rb
somerville-teacher-tool > db > seeds > demo > demo_students.seeds.rb

**Comment by alexsoble** [comment]
Question @marimuraki — as with attendance events above, can we calculate the percentage of students who have no discipline events?

**Comment by marimuraki** [comment]
School Year | Incident | N
------------ | ------------- | -------------
2015 | 7.5% | 4823

So:
- ~7.5% of active students have behavior incidents in 2015
