### ISSUE TITLE
Import parent contact information

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#95]
* Makes it easy for teachers to contact parents if they have a concern 
* Add field to students_export.sql script

**Comment by marimuraki** [comment]
Emergency contact = `STD_CTJ_OID_{1, 2, 3}` in STUDENT table
- only 33 non-missing for `STD_CTJ_OID_1` in current export

**Comment by alexsoble** [comment]
Ran some COUNT queries: 

```
SELECT COUNT(*) totalcount
FROM student_contact
-- 8623
```

```
SELECT COUNT(*) totalcount
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_CTJ_OID_1 IS NOT NULL
-- 33
```

```
SELECT COUNT(*) totalcount
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_CTJ_OID_2 IS NOT NULL
-- 15
```

```
SELECT COUNT(*) totalcount
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_CTJ_OID_3 IS NOT NULL
-- 6
```

Summary: The `student_contact` table has many records but almost no links exist to it from the `student` table exist on variables `STD_CTJ_OID_{1, 2, 3} `.

**Comment by alexsoble** [comment]
Parent/guardian names but no contact information in `STD_FIELDC_001`.

**Comment by alexsoble** [comment]
Aha. We want to be looking at the `person` table.

**Comment by alexsoble** [comment]
Linked on `STD_PSN_OID`:

```
SELECT COUNT(*) totalcount
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
-- 5065
```

```
SELECT COUNT(*) totalcount
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_PSN_OID IS NOT NULL
-- 5065
```

```

**Comment by alexsoble** [comment]
Further complexity: `person` includes both students and their family members. Some DBOs in 1950s and 1960s, others in 2000s and 1990s.
