### ISSUE TITLE
Handle data irregularities with attendance

### ISSUE THREAD

**Issue by marimuraki** [codeforamerica/somerville-teacher-tool#96]
Examples of data issues with `event_date` in attendance data (based on 2015-05 export):
- attendance records occur in the past (invalid range)
  - year == 0003 (N=1), 0209 (1), 0210 (1), 1027 (1), 1813 (1)
- attendance records occur in the future i.e., occur after export date:
  - year == 2017 (N=1), 2020 (2), 2086 (1), 2173 (1), 2175 (1), 6209 (1)
- attendance records with invalid `event_date`

Similar issue to #91

**Comment by marimuraki** [comment]
Also need to exclude duplicates in terms of `state_id`, `absence`, `tardy`, `event_date` so not to double-count any attendance events.

**Comment by alexsoble** [comment]
### Status update

+ Future attendance records are discarded in X2 export script
+ Past attendance records with invalid range not being handled at this point
+ {absences} + {tardies} != 100% of events, need to investigate

**Comment by alexsoble** [comment]
Moved to https://github.com/studentinsights/studentinsights.
