### ISSUE TITLE
Handle edge cases for behavior & attendance charts

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#97]
How should we handle edge cases where a student has one or zero attendance/behavior events? Difficult to chart one or zero in a meaningful way. Let's put in some thought & design :two_hearts:. 

Screenshots of how the chart renders currently at one / zero:
![one graph](https://cloud.githubusercontent.com/assets/3209501/7763921/114fadfe-fffd-11e4-95ec-fb7d7ed68c8f.png)
![zero graph](https://cloud.githubusercontent.com/assets/3209501/7763927/1ce54a98-fffd-11e4-8774-3d63270327ba.png)

**Comment by AmirHadjihabib** [comment]
Here is a way to remove decimals. 

http://stackoverflow.com/questions/14238780/how-to-show-only-integer-values-on-yaxis-of-highchart

**Comment by AmirHadjihabib** [comment]
Here is a zero state. We can use it for all the options in the dropdown with proper wording change. I can look into how to use the svg so the icon is responsive. 

![student profile v7 - zero](https://cloud.githubusercontent.com/assets/4615904/7776473/2885da7a-0070-11e5-964e-d403cc1823b7.png)

**Comment by AmirHadjihabib** [comment]
Good read on SVGs in web

https://css-tricks.com/using-svg/

**Comment by marimuraki** [comment]
@AmirHadjihabib Love the zero-state design! <3 bonsai!

I like the wording as well:
- attendance: "[Student] has no absences on record."
- tardies: "[Student] has no tardies on record."
- behavior incidents: "[Student] has no behavior incidents on record."

**Comment by marimuraki** [comment]
@alexsoble: Can you explain the current issue with how students with **one** attendance/behavior event is displayed?

**Comment by alexsoble** [comment]
Hey @devin-liu! I am sitting next to you at Code for SF and this is a really interesting issue we are looking at together!  :0)  :+1:

**Comment by alexsoble** [comment]
Rounded out with https://github.com/codeforamerica/somerville-teacher-tool/commit/d4bf85eb81c76b286e8d2ce1c0599f8d921c5cfd and https://github.com/codeforamerica/somerville-teacher-tool/commit/818b4fa636a163f2b8e8c1110347fcff9b8c754f.
